### ISSUE TITLE
Query results in SR087 and Virtuoso crash

### ISSUE THREAD

**Issue by jakubklimek** [openlink/virtuoso-opensource#106]
Virtuoso 7 fd9fea9e7e805af1cdbccf3fe963721c049ab267
Query:
<pre><code>SELECT  ?s (sum(?o) AS ?sum)
WHERE
  { ?s ?p ?o }
GROUP BY ?s
LIMIT   100
</pre></code>
Results in:
<pre><code>Virtuoso 22003 Error SR087: Non numeric argument(s) to arithmetic operation '+'.

SPARQL query:
define sql:big-data-const 0 
# output-format:text/html

define sql:signal-void-variables 1 SELECT  ?s (sum(?o) AS ?sum)
WHERE
  { ?s ?p ?o }
GROUP BY ?s
LIMIT   100</pre></code>

<b>And Virtuoso crashes.</b>

Apparently, this query is used by https://github.com/pyvandenbussche/sparqles

**Comment by HughWilliams** [comment]
I have been able to recreate this with the VOS7 build which crashes on the second execution of the query. Testing with the latest internal archive this issue does not occur and thus will be fixes when the current updates to the VOS7 git archives is complete, which should be in the next few days.

Note also to get around the "Virtuoso 22003 Error SR087: Non numeric argument(s) to arithmetic operation '+'." error condition which occurs because the you are trying to perform a arithmetic operation on an "ANY" datatype field, you to cast it to an integer:

SELECT  ?s (sum (xsd:integer(?o)) AS ?sum)

WHERE

 { ?s ?p ?o }

GROUP BY ?s

LIMIT   100

but need the updated git archive for this to work also ...
