### ISSUE TITLE
SQ074 SP031: Function cannot be used in text of SPARQL query due to security restrictions

### ISSUE THREAD

**Issue by jgager** [openlink/virtuoso-opensource#1163]
I am migrating an existing database from an older 7.2 release (7.20.3215) to a newer one (7.20.3237). I followed the usual procedure for moving to a new release (checkpoint, shutdown, ensure empty trx file) and had no issues there.

There is a service account created in the database that is used by our application to create and update content in a graph. Since the update, we get an error when the service account attempts to make an update:

`SQ074: Line 1: SP031: SPARQL compiler: Function http://www.openlink.com/schemas/bif#__rdf_long_from_batch_params() cannot be used in the text of SPARQL due to security restrictions.`

 If I change the application to use the dba account, this error does not occur. So I assume that there are additional grants that need to be added to the service account, but I am not seeing anything obvious. Can someone please point me in the right direction?

**Comment by HughWilliams** [comment]
What is the actually query being run, and how/where is it being executed from (i.e., the Virtuoso SPARQL endpoint, SQL interface (ODBC/JDBC), or other means)?

**Comment by jgager** [comment]
Hi Hugh,
This is being executed through JDBC. The failure happens trying to set up a prepared statement for deletes (although I assume our insert prepared statement would fail too as it is set up after the delete statement). The prepared statement is:

``sparql delete from graph iri(??) {`iri(??)` `iri(??)` `bif:__rdf_long_from_batch_params(??,??,??)`}``

Thanks,
Jack

**Comment by TallTed** [comment]
Hi @jgager -- I'm commenting, because GitHub doesn't always send expected notices upon issue closure. We believe this issue is resolved by https://github.com/openlink/virtuoso-opensource/commit/adffa269ea64edbc5f011fc7140da80ffd070a11, which is currently only available if you build your own binary from [the `/develop/7/` branch](https://github.com/openlink/virtuoso-opensource/tree/develop/7). The fix will be part of the next numbered update, which may ship anytime in the next several months.
