### ISSUE TITLE
Restriction on number of deleted triples

### ISSUE THREAD

**Issue by achort** [openlink/virtuoso-opensource#1164]
I am using Virtuoso version 07.20.3237 and it seems that when trying to delete triples from a graph, only at most `ResultSetMaxRows` triples are deleted. E.g., executing `sparql DELETE WHERE { graph <mygraph-uri> { ?p ?q ?r } }` in `isql` will not delete all the triples in the graph if it contains more than `ResultSetMaxRows` triples. The same holds for more complex queries that delete parts of the graph.

**Comment by TallTed** [comment]
First thing, binaries labeled as 07.20.3237 roughly correspond to [v7.2.10](https://github.com/openlink/virtuoso-opensource/releases/tag/v7.2.10), shipped June 7. (The [specific `cvs_id` of your binary](https://vos.openlinksw.com/owiki/wiki/VOS/VirtCheckSvrVersionViaSparql) would pin down the exact code version.) I am not aware of any [changes since then](https://github.com/openlink/virtuoso-opensource/compare/v7.2.10...v7.2.11) that would impact your specific experience, but you may still want to update to [v7.2.11](https://github.com/openlink/virtuoso-opensource/releases/tag/v7.2.11), shipped September 26.

To your issue as written, we have [some quick answers](https://vos.openlinksw.com/owiki/wiki/VOS/VirtTipsAndTricksGuideDeleteLargeGraphs) that can be used when you're deleting *all* triples from a graph. Some additional details are discussed in [#1085](https://github.com/openlink/virtuoso-opensource/issues/1085).

`CLEAR GRAPH ...` via `/sparql` would generally be your best bet, but you can also use `DELETE FROM rdf_quad ...` through any SQL interface. If you choose the latter, we recommend that you also rebuild the free text indexes by using iSQL to run `VT_INDEX_DB_DBA_RDF_OBJ(0)`. The snippets in https://github.com/openlink/virtuoso-opensource/issues/1085#issuecomment-1352016679 provide detailed instructions for these options.

As that seems insufficient for your overall needs, I will have to ask others for input on this, as I've never needed to delete such large numbers of triples except when deleting all triples from a given graph.

**Comment by achort** [comment]
Indeed my use case is not to delete an entire graph, which can be done otherwise as you explain, but to delete a large part of a graph that matches certain triples patterns using a DELETE statement.

**Comment by pkleef** [comment]
The problem was a misplaced check. 

I just committed https://github.com/openlink/virtuoso-opensource/commit/60427f4c154a50f54efd0b12edc1242257418c89 on the [develop/7](https://github.openlinksw.com/virtuoso-opensource) branch.

**Comment by achort** [comment]
@pkleef 

Trying to test the above fix with a statement of the form
`sparql DELETE { graph [mygraph] { ?p ?q ?r } }  WHERE { graph [mygraph] { [conditions on ?p ?q ?r] } }`
I get 
`*** Error 42000: [Virtuoso Driver][Virtuoso Server]D1CTX: Hash dictionary is full, exceeded 10000 entries`
where `10000` is the value of `MaxConstructTriples`. 

So this fix ensures the consistency of the graph, since either all triples that should be deleted according to the `DELETE` statement are deleted, or none are deleted if their number exceeds `MaxConstructTriples`. However, I think that it does not solve the actual problem of deleting a large number of triples using the `DELETE` statement if their number happens to exceeds `MaxConstructTriples`.

One possible approach would possibly be to iteratively issue statements of the form 
`DELETE { graph [mygraph] { ?p ?q ?r } }  WHERE { graph [mygraph] { [conditions on ?p ?q ?r] } } LIMIT [MaxConstructTriples]`
to simulate the behavior before the fix, and, after each one, count the triples that still meet the criteria until none are left. 

However this will not work when some of the deleted triples are triples that are used to check the conditions. In particular, if in one iteration a set of triples satisfy the conditions, but not all triples corresponding to that set of triples that should be deleted are actually deleted, but only some of them, because the limit has been reached, then at the next iteration the conditions will possibly not be satisfied anymore, but there will be undeleted triples left that cannot be identified using the conditions.

**Comment by pkleef** [comment]
There are several options:

1. Set the `MaxConstructTriples` in `virtuoso.ini` to either some sufficiently large number like several billion or to `0` which means `unlimited`.

2. Use the combination of [SPASQL](https://medium.com/virtuoso-blog/spasql-about-8486deecba66) and a SQL cursor

In this case you would have to write a Virtuoso PL procedure that creates a cursor over sparql select, open cursor over select, and do delete by selection, e.g.:

```
 for select * from (sparql select ?s ?p ?o WHERE {...}) dt do
  { sparql delete ... }
```  

In both cases, the number of triples you are able to delete in one transaction is limited by the amount of memory you have in your system for the transaction records, controlled by the [`TransactionAfterImageLimit`](https://docs.openlinksw.com/virtuoso/virtuosotipsandtrickssparulupdatestrl/) setting. 

This can be addressed by setting the [`log_enable`](https://docs.openlinksw.com/virtuoso/fn_log_enable/) mode to `3`, to switch from manual commit mode to autocommit mode.
