### ISSUE TITLE
Run Virtuoso completely in-memory

### ISSUE THREAD

**Issue by gpicciuca** [openlink/virtuoso-opensource#1237]
Hello,
Does Virtuoso offer a way to run completely in-memory without any persistent storage?

This would imply that it would:
- Keep loaded data only in memory
- Forget everything when the process stops

Couldn't (yet) find anything about this in the documentation or anywhere else.

Thanks in advance!

**Comment by HughWilliams** [comment]
Virtuoso is an ACID database requiring persistent storage for operation and thus will always create such, and so cannot run complete in memory only.

The closest you can get it to start a [Virtuoso docker container](https://hub.docker.com/r/openlink/virtuoso-opensource-7) without mounting a persistent volume mount point, such that the database is created internally within docker, and then when the docker container is stopped the database would be discarded due to the lack of a volume mount point and on restart a new empty database would be created.
