### ISSUE TITLE
 How to use Sponge of Virtuoso actually? Could anybody show me a vivid example?

### ISSUE THREAD

**Issue by candlecao** [openlink/virtuoso-opensource#1299]
In my local Virtuoso, given a graph <http://localhost:8890/DAV/onlyOneTriple> — for a simplest example, with only one triple and one assertion of namespace, there is the content:

`@prefix wikidata:	<http://www.wikidata.org/entity/> .`
`<https://cantusdatabase.org/chant/467250> wikidata:P136 wikidata:Q582093 .`

Then, my query codes in ISQL are:

```pre
SPARQL
DEFINE input:grab-all "yes"
DEFINE input:grab-depth 2
DEFINE input:grab-limit 200

SELECT * 
FROM NAMED <http://localhost:8890/DAV/onlyOneTriple>
WHERE {
  GRAPH ?g {
    ?s ?p ?o .
    FILTER(STRSTARTS(STR(?o), "http://www.wikidata.org/entity/")) # Ensure the object is a Wikidata entity
  }
  SERVICE <https://query.wikidata.org/sparql> {
    ?o ?wikidataProperty ?wikidataValue .
  }
};
```

— These codes are modified with the help of GPT4 in order to grab related data from Wikidata.

Hereby, while according to the significance of sponge I understood, it can grab the external data, for example, from Wikidata; as long as there are Wikidata resources which have the same URI with the entities from <http://localhost:8890/DAV/Jun> (as shown in the example codes above), there must be data retrieved upon execution. However, as I executed as above, there was no data feeding back. Is there something wrong, or could somebody please illustrate with some other example codes which generates outcome?

**Comment by candlecao** [comment]
I tested:
When I input codes as below in Wikidata Query Service, it can find results:
```
SELECT ?property ?object
WHERE {
  SERVICE <https://query.wikidata.org/sparql> {
    <http://www.wikidata.org/entity/Q582093> ?property ?object .
    # Add additional patterns or filters here if needed
  }
}
LIMIT 100
```
So there must be something wrong about my codes above or with my understanding about sponge!?

**Comment by kidehen** [comment]
# Pure SPARQL-FED

```sparql
SELECT DISTINCT * 
WHERE {
       GRAPH ?g {
                  ?s ?p ?o .
                  FILTER(STRSTARTS(STR(?o), "http://www.wikidata.org/entity/")) 
                  # the FILTER ensures the object is a Wikidata entity
                }

      SERVICE <https://query.wikidata.org/sparql> {
      SELECT DISTINCT ?o ?wikidataProperty ?wikidataValue
      WHERE { ?o ?wikidataProperty ?wikidataValue .}
      LIMIT 20 
  }
}
```

Live example [Link](https://linkeddata.uriburner.com/sparql?default-graph-uri=&query=SELECT+DISTINCT+*+%0D%0AWHERE+%7B%0D%0A+++++++GRAPH+%3Fg+%7B%0D%0A++++++++++++++++++%3Fs+%3Fp+%3Fo+.%0D%0A++++++++++++++++++FILTER%28STRSTARTS%28STR%28%3Fo%29%2C+%22http%3A%2F%2Fwww.wikidata.org%2Fentity%2F%22%29%29+%23+Ensure+the+object+is+a+Wikidata+entity%0D%0A++++++++++++++++%7D%0D%0A%0D%0A++++++SERVICE+%3Chttps%3A%2F%2Fquery.wikidata.org%2Fsparql%3E+%7B%0D%0A++++++SELECT+DISTINCT+%3Fo+%3FwikidataProperty+%3FwikidataValue%0D%0A++++++WHERE+%7B+%3Fo+%3FwikidataProperty+%3FwikidataValue+.%7D%0D%0A++++++LIMIT+20+%0D%0A++%7D%0D%0A%7D&should-sponge=&format=text%2Fhtml&timeout=30000)

# Sponger URI de-reference

This requires existence of triple pattern comprising at least one local component, e.g., predicate denoted by `<http://wikiba.se/ontology#rank>`.

```sparql
DEFINE get:soft "soft"
# DEFINE input:grab-all "yes"
# DEFINE input:grab-depth 2
# DEFINE input:grab-limit 20
# DEFINE input:grab-iri 
DEFINE input:grab-var "o"

SELECT DISTINCT * 
WHERE {
       GRAPH ?g {
                  ?s <http://wikiba.se/ontology#rank> ?o .
                  FILTER(STRSTARTS(STR(?s), "http://www.wikidata.org/entity/")) 
                  # the FILTER ensures the object is a Wikidata entity
                }
      }
```

Live Example [Link](https://linkeddata.uriburner.com/sparql?default-graph-uri=&query=DEFINE+get%3Asoft+%22soft%22%0D%0A%23+DEFINE+input%3Agrab-all+%22yes%22%0D%0A%23+DEFINE+input%3Agrab-depth+2%0D%0A%23+DEFINE+input%3Agrab-limit+20%0D%0A%23+DEFINE+input%3Agrab-iri+%0D%0ADEFINE+input%3Agrab-var+%22o%22%0D%0A%0D%0ASELECT+DISTINCT+*+%0D%0AWHERE+%7B%0D%0A+++++++GRAPH+%3Fg+%7B%0D%0A++++++++++++++++++%3Fs+%3Chttp%3A%2F%2Fwikiba.se%2Fontology%23rank%3E+%3Fo+.%0D%0A++++++++++++++++++FILTER%28STRSTARTS%28STR%28%3Fs%29%2C+%22http%3A%2F%2Fwww.wikidata.org%2Fentity%2F%22%29%29+%23+Ensure+the+subject+is+a+Wikidata+entity%0D%0A++++++++++++++++%7D%0D%0A%7D%0D%0A&should-sponge=&format=text%2Fhtml&timeout=30000).

**Comment by candlecao** [comment]
Hello, thank you for your sharing. As for Pure SPARQL-FED, I copied the codes and executed them in my local SPARQL, but it prompted:
<img width="1278" alt="Screenshot 2024-06-13 at 21 01 10" src="https://github.com/openlink/virtuoso-opensource/assets/63447377/ec2b6f45-19ff-4322-b883-e6c148f7fc2d">
What's wrong and how could I solve it?

**Comment by kidehen** [comment]
Your instance isn't permitted to execute SPARQL-FED queries against Wikidata.

**Comment by candlecao** [comment]
> Your instance isn't permitted to execute SPARQL-FED queries against Wikidata.

before that, I did the granting for my virtuoso:
`SQL> GRANT EXECUTE ON "DB.DBA.SPARQL_SD_PROBE" TO "dba";`

**Comment by candlecao** [comment]
So what else should I do, please?

**Comment by HughWilliams** [comment]
What is the [Virtuoso version](https://community.openlinksw.com/t/interrogating-attributes-of-a-virtuoso-server-instance-via-sparql/3629) being used ?

Have you granted the `SPARQL_FED` and `SPARQL_LOAD_SERVICE_DATA` roles to the "SPARQL" user (or whatever user this SPARQL-FED query is being run as) to enable the [SPARQL Endpoint Capabilities](https://vos.openlinksw.com/owiki/wiki/VOS/VirtTipsAndTricksDiscoverSPARQFedCapabilitiesSPARQL) of the remote end point to be determined?

**Comment by candlecao** [comment]
My Virtuoso Version: 07.20.3240.
I just now did 
`GRANT SPARQL_LOAD_SERVICE_DATA TO "SPARQL";` in ISQL. 
But when I did `GRANT SPARQL_FED TO "SPARQL";`, it prompted: `The object "SPARQL_FED" does not exist.`
Then I did `GRANT SPARQL_SELECT TO "SPARQL";` according to chatGPT's advice, but it prompted: `The object "SPARQL" already have role "SPARQL_SELECT" assigned.`

Anyway, I re-executed the 
```sparql
SELECT DISTINCT * 
WHERE {
       GRAPH ?g {
                  ?s ?p ?o .
                  FILTER(STRSTARTS(STR(?o), "http://www.wikidata.org/entity/")) 
                  # the FILTER ensures the object is a Wikidata entity
                }

      SERVICE <https://query.wikidata.org/sparql> {
         SELECT DISTINCT ?o ?wikidataProperty ?wikidataValue
         WHERE { ?o ?wikidataProperty ?wikidataValue .}
         LIMIT 20 
      }
}
```
, but there was still the error:
`Virtuoso RDFZZ Error DB.DBA.SPARQL_REXEC('https://query.wikidata.org/sparql', ...) returned Content-Type 'text/plain' status 'HTTP/1.1 400 Bad Request'`

**Comment by kidehen** [comment]
Please repeat your test using DBpedia. The goal being to determine if this relates to Wikidata's need to register accepted SPARQL-FED clients.

**Comment by TallTed** [comment]
@kidehen — 

> Please repeat your test using DBpedia.

If I understand your suggestion, you mean to try running the "pure SPARQL-FED" query through the DBpedia SPARQL endpoint?

That fails because the [`dbpedia.org/sparql` endpoint](https://dbpedia.org/sparql?default-graph-uri=http%3A%2F%2Fdbpedia.org&query=SELECT+DISTINCT+*+%0D%0AWHERE+%7B%0D%0A+++++++GRAPH+%3Fg+%7B%0D%0A++++++++++++++++++%3Fs+%3Fp+%3Fo+.%0D%0A++++++++++++++++++FILTER%28STRSTARTS%28STR%28%3Fo%29%2C+%22http%3A%2F%2Fwww.wikidata.org%2Fentity%2F%22%29%29+%0D%0A++++++++++++++++++%23+the+FILTER+ensures+the+object+is+a+Wikidata+entity%0D%0A++++++++++++++++%7D%0D%0A%0D%0A++++++SERVICE+%3Chttps%3A%2F%2Fquery.wikidata.org%2Fsparql%3E+%7B%0D%0A+++++++++SELECT+DISTINCT+%3Fo+%3FwikidataProperty+%3FwikidataValue%0D%0A+++++++++WHERE+%7B+%3Fo+%3FwikidataProperty+%3FwikidataValue+.%7D%0D%0A+++++++++LIMIT+20+%0D%0A++++++%7D%0D%0A%7D%0D%0A&format=text%2Fhtml&timeout=30000&signal_void=on&signal_unconnected=on) is not configured to permit anonymous outbound SPARQL-FED (`Virtuoso 42000 Error SQ070:SECURITY: Must have SELECT privileges on view DB.DBA.SPARQL_SINV_2 for group ID 111 (SPARQL), user ID 111 (SPARQL)`).  

The same query succeeds against the [`dbpedia.openlinksw.com/sparql` endpoint](https://dbpedia.openlinksw.com/sparql?default-graph-uri=&query=SELECT+DISTINCT+*+%0D%0AWHERE+%7B%0D%0A+++++++GRAPH+%3Fg+%7B%0D%0A++++++++++++++++++%3Fs+%3Fp+%3Fo+.%0D%0A++++++++++++++++++FILTER%28STRSTARTS%28STR%28%3Fo%29%2C+%22http%3A%2F%2Fwww.wikidata.org%2Fentity%2F%22%29%29+%0D%0A++++++++++++++++++%23+the+FILTER+ensures+the+object+is+a+Wikidata+entity%0D%0A++++++++++++++++%7D%0D%0A%0D%0A%23++++++SERVICE+%3Chttps%3A%2F%2Fquery.wikidata.org%2Fsparql%3E+%7B%0D%0A%23+++++++++SELECT+DISTINCT+%3Fo+%3FwikidataProperty+%3FwikidataValue%0D%0A%23+++++++++WHERE+%7B+%3Fo+%3FwikidataProperty+%3FwikidataValue+.%7D%0D%0A%23+++++++++LIMIT+20+%0D%0A%23++++++%7D%0D%0A%7D%0D%0A%0D%0A&format=text%2Fhtml&timeout=120000&signal_void=on&signal_unconnected=on), which appears to have somewhat different permissions set. 

This success suggests that Wikidata is not blocking SPARQL-FED clients.

**Comment by kidehen** [comment]
@TallTed, 

I am saying that Wikidata doesn't allow SPARQL-FED access to unknown sources. Our URIBurner instance is registered with Wikidata, so the test should be repeated there. Once confirmed, URIBurner can then be used as the proxy for achieving the original objective.

**Comment by candlecao** [comment]
Hello, thank you everyone. My problem is mostly resolved.
