### ISSUE TITLE
VOS7 Query execution time estimation way off

### ISSUE THREAD

**Issue by jakubklimek** [openlink/virtuoso-opensource#130]
VOS7 2701d3f242a630562302471d168d20fec5ed2805

For this query I get:

<pre><code>
Virtuoso 42000 Error The estimated execution time 881833 (sec) exceeds the limit of 80000 (sec).

SPARQL query:
PREFIX s: &lt;http://schema.org/&gt;
PREFIX gr: &lt;http://purl.org/goodrelations/v1#&gt;
PREFIX gml: &lt;http://www.opengis.net/ont/gml#&gt;
PREFIX adms: &lt;http://www.w3.org/ns/adms#&gt;
PREFIX skos: &lt;http://www.w3.org/2004/02/skos/core#&gt;
CONSTRUCT {
 ?kontrola s:geo ?c ;
      s:title ?objectName;
      s:description ?desc.
?c s:latitude ?lat; s:longitude ?lng .
} 
FROM &lt;http://linked.opendata.cz/resource/dataset/coi.cz/kontroly-sankce-zakazy&gt;
FROM &lt;http://linked.opendata.cz/resource/dataset/geocoordinates/google/schema.org&gt;
FROM &lt;http://linked.opendata.cz/resource/dataset/ares/or&gt;
WHERE {
?kontrola a s:CheckAction ;
      s:location ?address ;
      s:location/s:geo ?c ;
      s:object ?object.
?object adms:identifier/skos:notation ?ic .
OPTIONAL {?object gr:legalName ?objectName .}
?c s:longitude ?lng; 
        s:latitude ?lat .
?address s:streetAddress ?street;
              s:addressLocality ?locality;
              s:postalCode ?psc .
BIND (CONCAT('&lt;a href="', ?object, '"&gt;', COALESCE(CONCAT(?ic, ': ', ?objectName), ?ic), '&lt;/a&gt;\n', ?street, '\n', ?psc, ' ', ?locality) as ?desc)
}</code></pre>

It takes about 10-20 seconds to execute (when I set the estimation limit above 900 000 seconds)

**Comment by jakubklimek** [comment]
And after update to 58a84504919b39d802df541d2f76a54f1bfa3ba7
it said <code>The estimated execution time 26178044 (sec) exceeds the limit of 8000000 (sec).</code> and after setting the limit higher again, it actually took so long that I had to kill it.

After downgrade to 2701d3f242a630562302471d168d20fec5ed2805 it took 20s again. So there is yet another problem with the recent updates.

**Comment by openlink** [comment]
Can you please try with the absolute latest version from develop/7 as we made some fixes to the cost based optimizer since you logged this issue.

if this still fails, please generate an explain plan with both old and latest virtuoso-t binary so we can check the difference.

To make explain plain, connect with the isql tool to your database and perform the following commands:

SQL>  SET EXPLAIN ON;
SQL> SPARQL PREFIX ……….    ;
SQL> SET EXPLAIN OFF;

You can send the output of both explains to vos.admin@openlinksw.com so i can pass it on to development for analysis

**Comment by openlink** [comment]
Additionally try the method in this document with the latest binary as it will report both compiler and query execution plans and times:

http://docs.openlinksw.com/virtuoso/databaseadmsrv.html#readingqueryprofile

**Comment by jakubklimek** [comment]
OK, with 788bb9da315b19605856091726079338320e6212 I get:
<code>Virtuoso 42000 Error The estimated execution time 51696588 (sec) exceeds the limit of 3600 (sec).</code> and the query really takes forever so I am going to profile this.

**Comment by jakubklimek** [comment]
I sent you the explains to the email mentioned. The profiling requires the query to actually finish (if I understand it correctly) which is a bit of a problem because it just runs on and on with the up to date version... will wait a bit longer

**Comment by openlink** [comment]
I have forwarded your information to the virtdev team.

**Comment by jakubklimek** [comment]
OK, the query is still running, I will stop it :) as I said, in the older version it takes 20 seconds :)

**Comment by HughWilliams** [comment]
Hi Jakub,

I think asked you last week if it would be possible to get a copy of this database to recreate this problems in house, but I may have missed your response in all the updates that have come in recently, thus is this possible assuming there is not sensitive/private information in them ?

**Comment by jakubklimek** [comment]
Oh, I missed that. I just ran into this problem with another query ran on our public endpoint, so I will send you a link via email for download and the appropriate query. It said 600M seconds estimate and when I raised the limit, it evaluated in 1 second into empty turtle :)

**Comment by HughWilliams** [comment]
Jakub,

The develop/7 branch has a fix to enable the above query to now run successfully against the test DB you provided i.e.

SPARQL query:
PREFIX s: http://schema.org/
PREFIX gr: http://purl.org/goodrelations/v1#
PREFIX gml: http://www.opengis.net/ont/gml#
PREFIX adms: http://www.w3.org/ns/adms#
PREFIX skos: http://www.w3.org/2004/02/skos/core#
CONSTRUCT {
 ?kontrola s:geo ?c ;
      s:title ?objectName;
      s:description ?desc.
?c s:latitude ?lat; s:longitude ?lng .
} 
FROM http://linked.opendata.cz/resource/dataset/coi.cz/kontroly-sankce-zakazy
FROM http://linked.opendata.cz/resource/dataset/geocoordinates/google/schema.org
FROM http://linked.opendata.cz/resource/dataset/ares/or
WHERE {
?kontrola a s:CheckAction ;
      s:location ?address ;
      s:location/s:geo ?c ;
      s:object ?object.
?object adms:identifier/skos:notation ?ic .
OPTIONAL {?object gr:legalName ?objectName .}
?c s:longitude ?lng; 
        s:latitude ?lat .
?address s:streetAddress ?street;
              s:addressLocality ?locality;
              s:postalCode ?psc .
BIND (CONCAT('<a href="', ?object, '">', COALESCE(CONCAT(?ic, ': ', ?objectName), ?ic), '</a>\n', ?street, '\n', ?psc, ' ', ?locality) as ?desc)
}

For the query:

PREFIX gr: http://purl.org/goodrelations/v1#
PREFIX skos: http://www.w3.org/2004/02/skos/core#
PREFIX ruian: http://ruian.linked.opendata.cz/ontology/
PREFIX rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
PREFIX ec: http://ec.europa.eu/eurostat/ramon/ontologies/geographic.rdf#

construct {
?region a skos:Concept;
     rdf:value ?numofchecks;
     skos:prefLabel ?regionName;
     skos:broader ?lau1.
?lau1 a skos:Concept;
     skos:prefLabel ?lau1Name;
     skos:broader ?nuts3.
?nuts3 a skos:Concept;
     skos:prefLabel ?nuts3Name;
     skos:broader ?nuts2.
?nuts2 a skos:Concept;
     skos:prefLabel ?nuts2Name;
     skos:broader ?nuts1.
?nuts1 a skos:Concept;
     skos:prefLabel ?nuts1Name.
}
from http://linked.opendata.cz/resource/dataset/czso.cz/regions
from http://linked.opendata.cz/resource/dataset/coi.cz/kontroly-sankce-zakazy
from http://linked.opendata.cz/resource/dataset/ares/or
where
{
?ca a s:CheckAction;
   s:location ?location;
   s:object ?object.
?location s:location ?region.
?region a ec:LAURegion;
 dcterms:title ?regionName;
 ec:hasParentRegion ?lau1.
?lau1 dcterms:title ?lau1Name;
 ec:hasParentRegion ?nuts3.
?nuts3 rdfs:label ?nuts3Name;
 ec:hasParentRegion ?nuts2.
?nuts2 rdfs:label ?nuts2Name;
 ec:hasParentRegion ?nuts1.
?nuts1 rdfs:label ?nuts1Name.
{SELECT count(?cas) as ?numofchecks where {?cas s:location/s:location ?region.} group by ?region }
}

Development indicate the problem is that ?region inside

{SELECT count(?cas) as ?numofchecks where {?cas s:location/s:location ?region.} group by ?region }

has nothing common with ?region in

?location s:location ?region

Thus the subquery should be

{SELECT ?region count(?cas) as ?numofchecks where {?cas s:location/s:location ?region.} group by ?region }

or, equivalently

{SELECT ?r as ?region count(?cas) as ?numofchecks where {?cas s:location/s:location ?r .} group by ?r }

The other query you reported also now runs i.e.

PREFIX gr: http://purl.org/goodrelations/v1#
PREFIX skos: http://www.w3.org/2004/02/skos/core#
PREFIX ruian: http://ruian.linked.opendata.cz/ontology/
PREFIX rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
PREFIX ec: http://ec.europa.eu/eurostat/ramon/ontologies/geographic.rdf#

construct {
?region a skos:Concept;
     skos:prefLabel ?regionName;
s:location ?location;
     skos:broader ?lau1.
?lau1 a skos:Concept;
     skos:prefLabel ?lau1Name;
     skos:broader ?nuts3.
?nuts3 a skos:Concept;
     skos:prefLabel ?nuts3Name;
     skos:broader ?nuts2.
?nuts2 a skos:Concept;
     skos:prefLabel ?nuts2Name;
     skos:broader ?nuts1.
?nuts1 a skos:Concept;
     skos:prefLabel ?nuts1Name.
}
from http://linked.opendata.cz/resource/dataset/coi.cz/kontroly-sankce-zakazy
from http://linked.opendata.cz/resource/dataset/czso.cz/regions
from http://ec.europa.eu/eurostat/ramon/rdfdata/nuts2008/
where 
{
?region a ec:LAURegion;
 dcterms:title ?regionName;
 ^s:location/^s:location ?location ;
 ec:hasParentRegion ?lau1.
?lau1 dcterms:title ?lau1Name;
 ec:hasParentRegion ?nuts3.
?nuts3 rdfs:label ?nuts3Name;
 ec:hasParentRegion ?nuts2.
?nuts2 rdfs:label ?nuts2Name;
 ec:hasParentRegion ?nuts1.
?nuts1 rdfs:label ?nuts1Name.
}

Please check these yourself ...

**Comment by jakubklimek** [comment]
I confirm that now the queries work. Thanks :)
