### ISSUE TITLE
Content negotiation is broken for SPARQL result formats

### ISSUE THREAD

**Issue by namedgraph** [openlink/virtuoso-opensource#1321]
Our Linked Data client is using an `Accept` request header that prefers RDF but also accepts SPARQL results.
However Virtuoso response to this with a non-standard RDF serialization of the results set while in my opinion it should have returned `application/sparql-results+json` or `application/sparql-results+xml`.
```bash
curl -H "Accept: application/n-triples;q=0.9, x/ld-json-10;q=0.8, application/rdf+xml;q=0.8, x/ld-json-11;q=0.8, application/rdf+json;q=0.8, application/rdf+thrift, text/rdf+n3;q=0.8, application/rdf+protobuf;q=0.8, application/trix;q=0.8, text/turtle;q=0.8, application/ld+json;q=0.8, application/sparql-results+xml;q=0.6, text/tab-separated-values;q=0.5, text/csv;q=0.5, application/sparql-results+protobuf;q=0.7, application/sparql-results+thrift;q=0.7, application/sparql-results+json;q=0.6" 'https://dbpedia.org/sparql?query=SELECT%20DISTINCT%20*%0AWHERE%0A%7B%0A%20%3Fs%20%3Fp%20%3Fo%0A%7D%0ALIMIT%20100' -I
HTTP/2 200
date: Sun, 06 Oct 2024 17:40:50 GMT
content-type: application/n-triples; charset=UTF-8
content-length: 97295
server: Virtuoso/08.03.3331 (Linux) x86_64-generic-linux-glibc212  VDB
content-disposition: filename=sparql_2024-10-06_17-38-26Z.nt
expires: Sun, 13 Oct 2024 17:40:50 GMT
cache-control: max-age=604800
access-control-allow-credentials: true
access-control-allow-methods: HEAD, GET, POST, OPTIONS
access-control-allow-headers: Depth,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Accept-Encoding
```

**Comment by namedgraph** [comment]
BlazeGraph on Wikidata responds with `application/sparql-results+xml` as expected:
```bash
curl -I -H "Accept: application/n-triples;q=0.9, x/ld-json-10;q=0.8, application/rdf+xml;q=0.8, x/ld-json-11;q=0.8, application/rdf+json;q=0.8, applicat
ion/rdf+thrift, text/rdf+n3;q=0.8, application/rdf+protobuf;q=0.8, application/trix;q=0.8, text/turtle;q=0.8, application/ld+json;q=0.8, application/sparql-results+xml;q=0.6, text/tab-separated-values;q=0.5, text/csv;q=0.5, application/s
parql-results+protobuf;q=0.7, application/sparql-results+thrift;q=0.7, application/sparql-results+json;q=0.6" 'https://query.wikidata.org/sparql?query=SELECT%20DISTINCT%20*%0AWHERE%0A%7B%0A%20%3Fs%20%3Fp%20%3Fo%0A%7D%0ALIMIT%20100'
HTTP/2 200
server: nginx/1.18.0
date: Sun, 06 Oct 2024 17:38:02 GMT
content-type: application/sparql-results+xml;charset=utf-8
x-first-solution-millis: 0
x-served-by: wdqs1012
access-control-allow-origin: *
access-control-allow-headers: accept, content-type, content-length, user-agent, api-user-agent
cache-control: public, max-age=300
vary: Accept
content-length: 32124
age: 103
x-cache: cp3073 hit, cp3073 pass
x-cache-status: hit-local
server-timing: cache;desc="hit-local", host;desc="cp3073"
strict-transport-security: max-age=106384710; includeSubDomains; preload
report-to: { "group": "wm_nel", "max_age": 604800, "endpoints": [{ "url": "https://intake-logging.wikimedia.org/v1/events?stream=w3c.reportingapi.network_error&schema_uri=/w3c/reportingapi/network_error/1.0.0" }] }
nel: { "report_to": "wm_nel", "max_age": 604800, "failure_fraction": 0.05, "success_fraction": 0.0}
x-client-ip: 87.63.70.228
accept-ranges: bytes
```

**Comment by TallTed** [comment]
You're passing a VERY long `Accept:` header, which doesn't appear to be written to do what you want it to. I'll start by breaking the value into one media type per line, dropping their separating commas, and re-ordering those lines to descend by your assigned `q` weights (note that an omitted `q` is treated as `q=1.0`) and then ascend alpha-order where the weights are equal. I'm also inserting a blank line between weight values.
```
application/rdf+thrift

application/n-triples;q=0.9

application/ld+json;q=0.8
application/rdf+json;q=0.8
application/rdf+protobuf;q=0.8
application/rdf+xml;q=0.8
application/trix;q=0.8
text/rdf+n3;q=0.8
text/turtle;q=0.8
x/ld-json-10;q=0.8
x/ld-json-11;q=0.8

application/sparql-results+protobuf;q=0.7
application/sparql-results+thrift;q=0.7

application/sparql-results+xml;q=0.6
application/sparql-results+json;q=0.6

text/tab-separated-values;q=0.5
text/csv;q=0.5
```

Based *solely* on the above, I would expect Virtuoso to deliver `application/n-triples` (as it does), because it's your highest-weighted media type. (Note that servers are permitted to have their own `q` ratings for media types, and [the "effective" `q` is the product of multiplying the client's against the server's for each type](https://www.w3.org/DesignIssues/Conneg). This does not come into play in this issue, but it's an important thing to recognize when working against servers which you do not control.)

You seem to be suggesting that `application/n-triples` is a "non-standard RDF serialization", but this is [the correct media type for N-Triples 1.1](https://www.w3.org/TR/n-triples/#n-triples-mediatype). Please provide more detail about the "non-standard RDF serialization" you're seeing, if you meant something else.

If, as it seems, your actual preferences for the results format differ from the order seen above, I strongly recommend you assign *different* weights to each media type, such that they accurately reflect your *actual* preferences.

I do note several "non-standard RDF serialization" media types in your `Accept:` header (e.g., `x/ld-json-10`, `x/ld-json-11`). I suggest that you remove these from the list, unless you know your requests are sometimes going to servers that don't support the standard media type for the serializations you want.

I also note an apparent typo, `application/trix`. I bet you meant `application/trig`.

Finally, regarding —
> BlazeGraph on Wikidata responds with `application/sparql-results+xml` as expected:

That may be *your* expectation, but it is not what *I* would expect, unless BlazeGraph is configured (possibly only for the Wikidata endpoint) to set a very high `q` for `application/sparql-results+xml` and/or very low `q` for the other media types in your `Accept:` header, such that `application/sparql-results+xml` has the highest *effective* `q`.

Please let me know if the above comments are sufficient to resolve your concern.

**Comment by namedgraph** [comment]
> You're passing a VERY long Accept: header, which doesn't appear to be written to do what you want it to

The header is generated by our Linked Data client (from the formats registered in Jena's I/O) and generally does what it is intended to do -- make sure that either (preferably) an RDF graph response would be returned, or otherwise tabular SPARQL results.

> Please provide more detail about the "non-standard RDF serialization" you're seeing, if you meant something else.

My point is that N-Triples are non-standard serialization for _tabular SPARQL results_ -- note that this is a `SELECT` query. The RDF media types shouldn't even be in the set of types considered for conneg here.

`application/trix` is an XML-based quad format :) https://en.wikipedia.org/wiki/TriX_(serialization_format)

**Comment by TallTed** [comment]
> My point is that N-Triples are non-standard serialization for tabular SPARQL results

OK, but *you are (or at least your Linked Data client is) requesting them!* Virtuoso is simply delivering your query results in the highest-ranked serialization you have requested that it recognizes and supports, as is [specified by the HTTP RFC](https://www.rfc-editor.org/rfc/rfc9110.html#name-content-negotiation)!

If you prefer "an RDF graph response" for some queries, then your `Accept:` header for those queries should set those media types to a higher `q` than the less desirable "tabular SPARQL results" media types, which should in turn have a higher `q` than even-less desirable but still acceptable media types. 

I think that `Accept:` header "generally does" NOT do "what it is intended to do". You've just been lucky in whatever servers you've used that Linked Data client against, in that they have not conformed to [HTTP RFC's Content Negotiation](https://www.rfc-editor.org/rfc/rfc9110.html#name-content-negotiation), but they have delivered what you hoped for.

(Note that `application/trix`, `application/rdf+thrift`, `application/sparql-results+thrift`, `application/rdf+protobuf`, `application/sparql-results+protobuf`, `text/rdf+n3`, and possibly others in your current `Accept:` header, are not [IANA-registered media types](https://www.iana.org/assignments/media-types/media-types.xhtml). I would expect undesired and unpredictable results if relying on any of these, partially but not only because these media types could be stomped on by future IANA registrations and those future registrations could contain *anything*.)

**Comment by namedgraph** [comment]
> OK, but you are (or at least your Linked Data client is) requesting them!

I know, but try to write a generic header that is compatible with RDF and SPARQL results media types that doesn't do that?

I will try to prioritize the SPARQL result formats above the RDF formats and see if that solves the issue.

**Comment by TallTed** [comment]
> I know, but try to write a generic header that is compatible with RDF and SPARQL results media types that doesn't do that?

I believe I've provided sufficient detail above for you to do exactly that.

> I will try to prioritize the SPARQL result formats above the RDF formats and see if that solves the issue.

I look forward to reading of your success!

**Comment by namedgraph** [comment]
This version does the job:
```bash
curl -H "Accept: application/ld+json;q=0.5,text/turtle;q=0.5,application/rdf+xml;q=0.5,application/rdf+protobuf;q=0.5,application/rdf+json;q=0.5,application/trix;q=0.5,application/n-triples;q=0.6,text/rdf+n3;q=0.5,application/rdf+thrift;q=0.7,x/ld-json-10;q=0.5,x/ld-json-11;q=0.5,text/shaclc;q=0.5,application/sparql-results+xml;q=0.9,text/tab-separated-values;q=0.8,text/csv;q=0.8,application/sparql-results+protobuf,application/sparql-results+thrift,application/sparql-results+json;q=0.9" 'https://dbpedia.org/sparql?query=SELECT%20DISTINCT%20*%0AWHERE%0A%7B%0A%20%3Fs%20%3Fp%20%3Fo%0A%7D%0ALIMIT%20100' -I
```

**Comment by TallTed** [comment]
I'm glad that works for you, for now, against the servers you're testing today.

This is your new `Accept:` header, broken onto multiple lines, and ordered by `q` value and your current order (i.e., I've ignored the lexical media types).
```
application/sparql-results+protobuf,
application/sparql-results+thrift,

application/sparql-results+json;q=0.9,
application/sparql-results+xml;q=0.9,

text/tab-separated-values;q=0.8,
text/csv;q=0.8,

application/rdf+thrift;q=0.7,

application/n-triples;q=0.6,

application/ld+json;q=0.5,
text/turtle;q=0.5,
application/rdf+xml;q=0.5,
application/rdf+protobuf;q=0.5,
application/rdf+json;q=0.5,
application/trix;q=0.5,
text/rdf+n3;q=0.5,
x/ld-json-10;q=0.5,
x/ld-json-11;q=0.5,
text/shaclc;q=0.5,
```

Please note that you have 3 decimals in which to specify the `q` values, i.e., `0.001`–`0.999` plus the `1.000`, so 1000 `q` values, total. I encourage you to assign *one* media type to any given `q` value in that range, and to order them according to your *actual* preference. I encourage you also to keep them in that order in the `Accept:` header — just to make your own life easier over time; as you will have noticed, it makes no difference to the software.

In your current header, the software sees *no* difference in preference between any media types with the same `q` value. You're effectively asking for a coin toss (or die roll) across each group. Knowing, for instance, that the `+xml` types are substantially wordier than the `+json`, I'm fairly confident that there *is* a preference between those two `q=0.9` types.
