### ISSUE TITLE
Dump one graph in Virtuoso 7.1

### ISSUE THREAD

**Issue by white-gecko** [openlink/virtuoso-opensource#206]
I'm on virtuoso 7.1 (current `develop/7` branch) and the procedure `dump_one_graph` is not predefined in `isql-v`. (I build virtuoso from current git `develop/7` branch with `dpkg_buildpackage`).
I've defined the procedure by pasting the code from the [wiki](http://virtuoso.openlinksw.com/dataspace/doc/dav/wiki/Main/VirtRDFDatasetDump), but when I execute the procedure I get following error:

```
*** Error 22023: [Virtuoso Driver][Virtuoso Server]SR601: Argument 0 of http_ttl_triple() should be an array of special format
```

`http_ttl_triple()` is called in line 36 of the procedure definition.

Is this procedure definition not compatible with 7.1 anymore?

Please see also: http://boards.openlinksw.com/support/viewtopic.php?f=12&t=6272

**Comment by HughWilliams** [comment]
This is already reported in https://github.com/openlink/virtuoso-opensource/issues/188 for development to fix , thus please track that issue for fix ...

**Comment by HughWilliams** [comment]
This has been fixed with an updated procedure added to:

```
http://virtuoso.openlinksw.com/dataspace/doc/dav/wiki/Main/VirtRDFDatasetDump
```

Which now gives:

SQL> dump_one_graph ('http://linked.opendata.cz/resource/dataset/seznam.gov.cz/agendy_new', './data_', 1000000000);

Done. -- 837 msec.
SQL>

[root@masala vos]# ls -ltr data_000001.ttl.*
-rw-r--r--. 1 root root     67 Sep 29 03:07 data_000001.ttl.graph
-rw-r--r--. 1 root root 637583 Sep 29 03:07 data_000001.ttl.gz
[root@masala vos]#

**Comment by LaurensRietveld** [comment]
Tried to store this procedure, and got a 'SQ074: Line 72: syntax error' error

VOS
Version: 07.10.3207
Build: Aug 20 2014

update: removing the last semi-colon fixed this syntax error

**Comment by jindrichmynarz** [comment]
I had the same experience as @LaurensRietveld (using a5e1f5bb055761c389ea50f8f8849b73e5241018). It would be great if the last semi-colon could be deleted in the documentation.
