### ISSUE TITLE
SQL State 42001 when adding a new WebDAV property (on Windows)

### ISSUE THREAD

**Issue by robertoea** [openlink/virtuoso-opensource#223]
Perhaps related to https://github.com/openlink/virtuoso-opensource/issues/154:

I got the following error message when trying to add a new WebDAV folder property:

```
Error
Stop
An error has occurred when processing "/conductor/cont_page.vspx" page.
SQL State   42001
SQL Message     

SR185: Undefined procedure DB.DBA.ACL_VALIDATE.
```

I am runnning:
Virtuoso Open Source Edition (multi threaded)
Version 7.1.0.3211-threads as of Jul 10 2014
Compiled for Win64 (x86_64-generic-win-64)

with
conductor   1.00.8727/ 2014-07-28 

on a Windows Server 2012 machine.

**Comment by HughWilliams** [comment]
I have been able to recreate this issue adding a new WeDAV folder property and assigned to development to look into ...

**Comment by dixonrl** [comment]
I am getting similar error when trying to upload an XSL file:

Error occurred when processing "/conductor/popup_browser.vspx" page.
SQL State 
42001 
SQL Message 
SR185: Undefined procedure DB.DBA.ACL_VALIDATE

Version 07.10.3207-pthreads for Linux as of Aug  6 2014
Virtuoso Conductor version 1.00.8727 (DAV)

CENTOS 6.5 VM

Is there any update?

**Comment by HughWilliams** [comment]
This is a known issue with the 3207 builds from stable/7 which is fixed in develop/7 as indicated in issue:

https://github.com/openlink/virtuoso-opensource/issues/154#issuecomment-43514250

Thus please update to the Virtuoso git develop/7 branch as detailed at:

http://virtuoso.openlinksw.com/dataspace/doc/dav/wiki/Main/VOSGitUsage
