### ISSUE TITLE
dump_one_graph not working again

### ISSUE THREAD

**Issue by jakubklimek** [openlink/virtuoso-opensource#276]
dump_one_graph stopped working after https://github.com/openlink/virtuoso-opensource/issues/188 was resolved for a short while. Now in 7f6f9390a3524eb1dd71668cbab51ccea224b25c I get:

<pre><code>
SQLState: 42S22
Message: SQ063: No column http://linked.opendata.cz/resource/dataset/vavai/projects.
 dump_one_graph("http://linked.opendata.cz/resource/dataset/vavai/projects", "/data/virtuoso/upload", 1000000000000)</code></pre>

I get the source from http://virtuoso.openlinksw.com/dataspace/doc/dav/wiki/Main/VirtRDFDatasetDump

**Comment by HughWilliams** [comment]
@jakubklimek I have been able to recreate this and reported to development to fix ...

**Comment by HughWilliams** [comment]
@jakubklimek : Hmmm, actually this is not a problem ... you are using double quotes (") rather than single quotes (') for delimiting the string values in the procedure as indicated in the documentation at:

   http://virtuoso.openlinksw.com/dataspace/doc/dav/wiki/Main/VirtRDFDatasetDump

The following works for me:

SQL> sparql select count(*) from
http://linked.opendata.cz/resource/dataset/mfcr/rozvaha where {?s ?p ?o};
callret-0
INTEGER

---

24010658

1 Rows. -- 30 msec.
SQL> dump_one_graph('http://linked.opendata.cz/resource/dataset/mfcr/rozvaha',
'./data_', 1000000000000);

Done. -- 400818 msec.
SQL> quit;
[root@masala db04]# ls -ltr data_000001.ttl.g*
-rw-r--r--. 1 root root        55 Dec 23 12:05 data_000001.ttl.graph
-rw-r--r--. 1 root root 110414982 Dec 23 12:12 data_000001.ttl.gz
[root@masala db04]#
