### ISSUE TITLE
Virtuoso 7 adds 10 days to date

### ISSUE THREAD

**Issue by white-gecko** [openlink/virtuoso-opensource#292]
Adding the following triple will alter the date from `1582-10-10` to `1582-10-20`:

```
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix ex: <http://example.org/> .

ex:person ex:dateOfBirth "1582-10-10"^^xsd:date .
```

The same also happens to `1582-10-09` becoming `1582-10-19` and so on.

I've tested it on the latest `develop/7` branch and it also happens on Virtuoso 6.1.

**Comment by HughWilliams** [comment]
This problem has been recreated and reported to development to fix ...

**Comment by HughWilliams** [comment]
This problem has been fixed and pushed to the develop/7 branch. It was due to the date being neither Julian nor Gregorian as during Gregorian reform the Pope said that the next day after 1582-10-04 is 1582-10-15, to free the calendar from the accumulated error, thus 1582-10-10 is the date that never happened !!!

The  fix now check correctly checks and validates these dates should they be used as can be seen with the following query:

SQL> select nasa_tjd_number(cast ('1582-10-10' as date));
**\* Error 22007: VD [Virtuoso Server]DT006: Cannot convert 1582-10-10 to datetime : The notation 1582-10-10 refers to day that does not exist due to Gregorian reform, valid dates of that month are Julian 1 to 4 and Gregorean 15
to 31
SQL>

To have dates in the invalid range be displayed correct you will need to dump and reload them as I had to do for them to be displayed correctly:

SQL> sparql select \* from http://nat where {?s ?p ?o};
s                                                                                 p                                                                                 o
VARCHAR                                                                           VARCHAR                                                                           VARCHAR

---

http://example.org/person                                                         http://example.org/dateOfBirth                                                    1582-10-20

1 Rows. -- 0 msec.
SQL> sparql clear graph http://nat;

Done. -- 1 msec.
SQL> sparql select \* from http://nat where {?s ?p ?o};
s                                                                                 p                                                                                 o
VARCHAR                                                                           VARCHAR                                                                           VARCHAR

---

0 Rows. -- 0 msec.
SQL> 
SQL> 
SQL> ttlp (file_to_string_output ('./nat.n3'), '', 'http://nat', 0);

Done. -- 1 msec.
SQL> sparql select \* from http://nat where {?s ?p ?o};
s                                                                                 p                                                                                 o
VARCHAR                                                                           VARCHAR                                                                           VARCHAR

---

http://example.org/person                                                         http://example.org/dateOfBirth                                                    1582-10-10

1 Rows. -- 0 msec.
SQL>
