### ISSUE TITLE
Support standard MIME type of N-Triples

### ISSUE THREAD

**Issue by jindrichmynarz** [openlink/virtuoso-opensource#516]
The standard MIME type of N-Triples is `application/n-triples` (see the [specification](http://www.w3.org/TR/n-triples/)). When used as an `Accept` HTTP header, Virtuoso SPARQL endpoint rejects the request with `HTTP 406 Not acceptable` status code. Instead, Virtuoso uses `text/plain` as the MIME type for N-Triples. It would be nice if also the standard `application/n-triples` was supported.

**Comment by HughWilliams** [comment]
@jindrichmynarz: Can u provide an example  curl or other query that demonstrates this problem ?

**Comment by jindrichmynarz** [comment]
`curl -H "Accept:application/n-triples" --data-urlencode "query=CONSTRUCT WHERE { ?s ?p ?o . } LIMIT 10" http://dbpedia.org/sparql` returns `406 Not Acceptable`, whereas with `text/plain` Accept header response in N-Triples is returned.

**Comment by HughWilliams** [comment]
@jindrichmynarz: Thanks I can see the problem and have reported to development to look into ...

**Comment by retog** [comment]
* When setting the `Accept` header to `application/n-triples` one gets a 406 message
* When setting the `Accept` header to `text/plain` one gets n-triples  with Content-Type `text/plain`
* When setting the `Accept` header to `application/n-triple,text/plain` one gets turtle with the `content-Type`header set to `text/plain`
* When setting the `Accept` header to `text/turtle` one gets turtle with the `content-Type`header set to `text/turtle; charset=UTF-8`

**Comment by TallTed** [comment]
@retog, @jindrichmynarz -- checking [your latest test reports](https://github.com/openlink/virtuoso-opensource/issues/516#issuecomment-427841764) (which isn't trivial, as they were posted as descriptive text, rather than as command + result, as shown below)...

I ran these against VOS [`07.20.3230 (036b7b9) as of Sep 20 2018`](https://vos.demo.openlinksw.com/sparql?default-graph-uri=&query=PREFIX++bif%3A++%3Cbif%3A%3E%0D%0A%0D%0ASELECT%0D%0A++%28+bif%3Asys_stat%28%27st_dbms_name%27%29++++++++++AS+%3Fname+%29%0D%0A++%28+bif%3Asys_stat%28%27st_dbms_ver%27%29+++++++++++AS+%3Fversion+%29%0D%0A++%28+bif%3Asys_stat%28%27st_build_date%27%29+++++++++AS+%3Fbuild_date+%29%0D%0A%0D%0A%23%23+++The+following+line+must+be+commented+for+execution+on+%0D%0A%23%23+++builds+produced+before+the+switch+from+%60cvs%60+to+%60git%60%3B%0D%0A%23%23+++it+only+works+on+versions+later+than+v6.1.5%0D%0A%0D%0A++%28+bif%3Asys_stat%28%27git_head%27%29++++++++++++++AS+%3Fgit_head+%29+++%0D%0A%0D%0A++%28+bif%3Asys_stat%28%27st_build_thread_model%27%29+AS+%3Fthread+%29%0D%0A++%28+bif%3Asys_stat%28%27st_build_opsys_id%27%29+++++AS+%3Fopsys+%29%0D%0A%0D%0A%23%23+++The+following+two+lines+must+be+commented+for+execution+%0D%0A%23%23+++on+VOS%3B+these+only+work+on+Enterprise+Edition%0D%0A%0D%0A%23+%28+bif%3Asys_stat%28%27st_lic_owner%27%29++++++++++AS+%3Fowner+%29%0D%0A%23+%28+bif%3Asys_stat%28%27st_lic_serial_number%27%29++AS+%3Fserial+%29%0D%0A%0D%0AWHERE%0D%0A++%7B++%3Fs++%3Fp++%3Fo++%7D%0D%0ALIMIT+1%0D%0A&format=text%2Fhtml&timeout=0&debug=on&run=+Run+Query+)

* `curl -iH "Accept: application/n-triples" --data-urlencode "query=CONSTRUCT WHERE { ?s ?p ?o . } LIMIT 1" https://vos.demo.openlinksw.com/sparql`
  -> **`Content-Type: application/n-triples; charset=UTF-8`**

* `curl -iH "Accept: text/plain" --data-urlencode "query=CONSTRUCT WHERE { ?s ?p ?o . } LIMIT 1" https://vos.demo.openlinksw.com/sparql`
  -> **`Content-Type: text/plain; charset=UTF-8`**

* `curl -iH "Accept: application/n-triple,text/plain" --data-urlencode "query=CONSTRUCT WHERE { ?s ?p ?o . } LIMIT 1" https://vos.demo.openlinksw.com/sparql`
  @retog -- note typo `n-triple` -- missing `s` -- in your 3rd above
  -> **`Content-Type: text/turtle; charset=UTF-8`**

* `curl -iH "Accept: application/n-triples,text/plain" --data-urlencode "query=CONSTRUCT WHERE { ?s ?p ?o . } LIMIT 1" https://vos.demo.openlinksw.com/sparql`
  -> **`Content-Type: application/n-triples; charset=UTF-8`**

* `curl -iH "Accept: text/turtle" --data-urlencode "query=CONSTRUCT WHERE { ?s ?p ?o . } LIMIT 1" https://vos.demo.openlinksw.com/sparql`
  -> **`Content-Type: text/turtle; charset=UTF-8`**


I think the above results mean this issue may be closed.  What do you think?

**Comment by jindrichmynarz** [comment]
Yes, this looks good:

```sh
curl \
  --silent \
  --header "Accept:application/n-triples" \
  --data-urlencode "query=CONSTRUCT WHERE { ?s ?p ?o . } LIMIT 1" \
  --write-out "%{content_type}" \
  --output /dev/null \
  http://dbpedia.org/sparql
# => application/n-triples; charset=UTF-8
```
