### ISSUE TITLE
Missing property in the web interface of dbpedia

### ISSUE THREAD

**Issue by alkiskal** [openlink/virtuoso-opensource#580]
I'm not sure if this is the right place to report this. Please inform me if I am.

Check the results of the query below here http://dbpedia.org/sparql

```
SELECT * WHERE{
  <http://dbpedia.org/resource/Academic_Structure_of_the_Australian_National_University> ?p ?o
}
```

And check the results shown here http://dbpedia.org/page/Academic_structure_of_the_Australian_National_University

There are properties missing (rfd:type)

**Comment by openlink** [comment]
The problem here is that you are actually querying two different data pages. 

When you click on: 
  http://dbpedia.org/resource/Academic_Structure_of_the_Australian_National_University

you actually arrive on:
  http://dbpedia.org/page/Academic_structure_of_the_Australian_National_University

Notice the capital in '_structure_' is now lower case.

As per the [W3's HTML and URL spec](https://www.w3.org/TR/WD-html40-970708/htmlweb.html):

> URLs in general are case-sensitive (with the exception of machine names). There may be URLs, or parts of URLs, where case doesn't matter, but identifying these may not be easy. Users should always consider that URLs are case-sensitive. 

Whenever a page title gets changed in WIkipedia, or when multiple pages get merged in case several users created a page about the same subject, Wikipedia creates an automatic redirect record. 

When the DBpedia dumps are made, these redirects are preserved, and when requesting such pages DBpedia will do the same thing as Wikipedia and automatically direct you to the correct page.

However when using a simple SPARQL query like you used, this redirect is of course not performed as you may have wanted to look at the metadata for that original page.

In the result, you will however find the following triple: 

```
http://dbpedia.org/ontology/wikiPageRedirects       
http://dbpedia.org/resource/Academic_structure_of_the_Australian_National_University
```

which you can use in your code to detect you need to restart your query for this new target subject.
