### ISSUE TITLE
Error on Graph Management Posting

### ISSUE THREAD

**Issue by ebremer** [openlink/virtuoso-opensource#593]
posting

@prefix :      <http://xmlns.com/foaf/0.1/> .

[ :status "unhappy"
] .

to Virtuoso via the sparql-graph-crud generates the following error
HTTP/1.1 500 Request Failed
Error 37000
SP029: TURTLE RDF loader, line 4: Missing predicate and object between top-level blank node subject and a dot processed pending to here.

posting

@prefix :      <http://xmlns.com/foaf/0.1/> .

[ :status "unhappy"
]  a <http://www.w3.org/TR/2004/REC-owl-semantics-20040210/#owl_Thing> .

works.  Aren't both sets of ttl valid?

**Comment by mjovanovik** [comment]
Hi @ebremer, I managed to reproduce your issue. 

The first version of your triple is recognized by some tools as a correct syntax, but the official Turtle standard doesn't mention the ability to denote top-level blank nodes without them being involved in an actual triple. [All examples in the Turtle standard](https://www.w3.org/TR/turtle/#unlabeled-bnodes) have the top-level blank nodes as either subjects or objects of a triple.

Therefore, your first triple it's viewed in Virtuoso simply as `[...] .`

Hence the error that you're missing a predicate and an object, between the blank node and the dot.

You can solve this by using the following Turtle syntax ([see Example 15](https://www.w3.org/TR/turtle/#unlabeled-bnodes)):

```
@prefix : <http://xmlns.com/foaf/0.1/> .
[] :status "unhappy" .
```

**Comment by afs** [comment]
From the [grammar for Turtle](https://www.w3.org/TR/turtle/#sec-grammar-grammar) in the W3C specification:

```
[6]     triples     ::=     subject predicateObjectList | blankNodePropertyList predicateObjectList?
[14]    blankNodePropertyList   ::=     '[' predicateObjectList ']'
[7]     predicateObjectList     ::=     verb objectList (';' (verb objectList)?)*
```

so in production 6, `blankNodePropertyList predicateObjectList?`, the `predicateObjectList?` is optional and just `blankNodePropertyList` is accepted at production 6.

**Comment by IvanMikhailov** [comment]
This syntax was not valid in first versions of Turtle but it become so popular that Virtuoso's Turtle parser supported it when bit 64 is passed to the function... and then I overslept the moment of accepting the syntax as a part of W3C spec. That's of course fixed in next release, meanwhile almost any VOS version can be patched by a single-liner

diff --git a/libsrc/Wi/turtle_p.y b/libsrc/Wi/turtle_p.y
index a16ad76..092dfbf 100644
--- a/libsrc/Wi/turtle_p.y
+++ b/libsrc/Wi/turtle_p.y
@@ -373,7 +373,7 @@ inner_predicate_object_list
 top_blank_predicate_object_list_or_garbage_with_dot
    : top_blank_predicate_object_list _DOT_WS       { ttlp_triple_process_prepared (ttlp_arg); }
    | top_blank_predicate_object_list _GARBAGE_BEFORE_DOT_WS _DOT_WS        { ttlp_triple_forget_prepared (ttlp_arg); }
-   | _DOT_WS { TTLYYERROR_ACTION_COND (TTLP_ACCEPT_DIRTY_SYNTAX, "Missing predicate and object between top-level blank node subject and a dot"); }
-   | _DOT_WS /\* This was before Turtle 1.1: { TTLYYERROR_ACTION_COND (TTLP_ACCEPT_DIRTY_SYNTAX, "Missing predicate and object between top-level blank node subject and a dot"); } */
  | _GARBAGE_BEFORE_DOT_WS _DOT_WS
  | _LBRA_TOP_TRIG { ttlyyerror_action ("Virtuoso does not support blank nodes as graph identifiers inTriG, graphs are identified only by IRIs"); }
  ;
