### ISSUE TITLE
build from source for 7.2.4.2 and debian stretch

### ISSUE THREAD

**Issue by andrewufrank** [openlink/virtuoso-opensource#627]
i have a debian - stretch installation and  downloaded the archive, unpacked did autogen and configure. when i ` make `
i get the error message: 
````
In file included from ../../libsrc/odbcsdk/include/iodbcunix.h:79:0,
                 from ../../libsrc/odbcsdk/include/sql.h:87,
                 from odbcinc.h:72,
                 from sqlnode.h:31,
                 from bif_crypto.c:28:
/usr/include/stdlib.h:148:26: note: expected ‘const char * restrict’ but argument is of type ‘boxint {aka long long int}’
````
which seems to indicate a problem in the c code? any patch to fix? 
i tested with a github clone (latestet commit c30a3c711993b2f60d8e807c4bab8d717a56f28b) and obtain exactly the same error. it seems a small change in some interface?? please fix on github at least.
thank you!

i tried as well with `github - git checkout v7.2.0.1` commit `a5e1f5bb0` as i saw a report for success with this. the exact same error - i would assume that it is a difference in iodbcunix which changed between wheezy, jessie and stretch (which i am running).

what is the best debian and virtuoso 7 combination? what would run on jessie?

**Comment by openlink** [comment]
The problem is that the upcoming Debian 9 (stretch, currently release candidate 2) is using the new OpenSSL version 1.1.0 which has an incompatible API compared to OpenSSL 1.0.1 and earlier versions that have we used to develop Virtuoso with.

We are currently working on a big update for Virtuoso Open Source Edition and we will try to add support for OpenSSL 1.1.0 at the same time. This should hopefully happen before the new version of debian becomes their official release.

At this time the best Debian release would be Debian 8 (jessie) which is the stable version of Debian which has been tested with the develop/7.x branch of Virtuoso.

**Comment by andrewufrank** [comment]
thank you for your information - could you put this somewhere on the page where the instruction for from source installation are given - they are excellent and worked later on a jessie installation without a glitch.

**Comment by gabriel-lucas** [comment]
@openlink did you managed to solve the issue with OpenSSL?

Today I have been trying to use BIND and day(), month(), year() functions, but I found they are not supported in the 6.1 version in the debian repositories.
https://stackoverflow.com/questions/25654730/some-sparql-commands-dont-work-when-used-in-isql

Do you have an approximated date for the update?

thank you
