### ISSUE TITLE
make install does silently not copy all files - because gawk is missing

### ISSUE THREAD

**Issue by andrewufrank** [openlink/virtuoso-opensource#628]
the ./autogen.sh does not check for presence of gawk which is used in `make install`. 
when missing, the bin files are not copied.
(i did install on debian jessie with the `c30a3c711993b2f60d8e807c4bab8d717a56f28b` version from github (current)). 
could you add a check for gawk in autogen.sh? 
thank you - install works nicely!

**Comment by openlink** [comment]
A check for ***gawk*** has been part of autogen.sh since Mar 15, 2008 commit https://github.com/openlink/virtuoso-opensource/commit/ae5f8ff87c4e3ce366b0c606f39a0dbbe6230209:

```
$ sh autogen.sh

Checking build environment ...
Using aclocal (GNU automake) 1.15
Using autoconf (GNU Autoconf) 2.69
Using autoheader (GNU Autoconf) 2.69
Using automake (GNU automake) 1.15
Using glibtoolize (GNU libtool) 2.4.6
Using bison (GNU Bison) 2.3
Using flex 2.5.35 Apple(flex-31)

** ERROR ** : You must have 'gawk' installed on your system.

Using GNU gperf 3.0.3
Using OpenSSL 0.9.8zg 14 July 2015

Please read the README file for a list of packages you need
to install on your system before bootstrapping this project.

Bootstrap script aborting ...

```

The automake tool actually adds checks for: ***gawk***, ***mawk***, ***nawk***, or ***awk*** and uses the outcome in the install-bin rules it generates into Makefile.in. While it does not exit with an error if non of these awk variants are  found, you would not be able to run configure without it:

```
$ ./configure
. . .
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
./config.status: line 1661: awk: command not found
config.status: error: could not create Makefile
```

I will check the debian build files to make sure it lists gawk as part of its build dependency list.

**Comment by andrewufrank** [comment]
thank you!
