### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by ghost** [openlink/virtuoso-opensource#71]
Hi,

I tried to compile Virtuoso 7 and I fall on this error during the "make" step :

../../libsrc/Wi/.libs/libwi.a(libwi_la-disk.o): In function `wi_open':
disk.c:(.text+0x83b9): undefined reference to`mon_init'
../../libsrc/Wi/.libs/libwi.a(libwi_la-lock.o): In function `the_grim_lock_reaper':
lock.c:(.text+0x33aa): undefined reference to`mon_update'
lock.c:(.text+0x33b1): undefined reference to `mon_check'

I made the configure like this : 

./configure --prefix=/var/usr/virtuoso --program-transform-name="s/isql/isql-v/" --enable-dbpedia-vad --enable-rdfmappers-vad --enable-conductor-vad --enable-rdb2rdf-vad --enable-fct-vad

Anyone know from where this error can come from ?

**Comment by indeyets** [comment]
@jpluorange that's from recent commits. I guess "monitor" code (whatever that is) wasn't fully merged

**Comment by ghost** [comment]
Ok so I will wait the next commit :-) Thanks.

**Comment by openlink** [comment]
I think the problem is that you did not run configure with the --enable-maintainer-mode flag, so changed to configure.in or Makefile.am do not trigger a rebuild of the code.

Please pull the latest develop/7 and then perform the following commands:
- rerun autoconf, automake etc:
  
  sh autogen.sh
- return configure with the exact same parameters you used before:
  
  sh config.nice

After this you should be able to do:

```
make clean
make 
```

and get a working build

**Comment by ghost** [comment]
Indeed, it works now just with the "autogen.sh". Thank you.
