### ISSUE TITLE
Is there a way to optimize this particular query?

### ISSUE THREAD

**Issue by SteffRhes** [openlink/virtuoso-opensource#729]
Hi all, 
  
We have a working query for the following case, but it becomes very slow when querying our productive dataset. 

Basically we want to have the triples returned where the subjects have `<rdf:type>` property defined somewhere, but we don't want _only the triples returned where these type properties are defined._ e.g., assuming the following data:
```
s1 - rdf:type - t1
s1 - p - o1
s2 - p - o2
```
So we want to have returned:
```
s1 - rdf:type - t1
s1 - p - o1
```
since `s1` has type `property` while `s2` doesn't.

Our SPARQL query which works on small datasets but not very well on large sets (for 7 million triples it took 1 hour) is the following:

`SELECT * WHERE { ?s ?p ?o . { SELECT DISTINCT (?s) WHERE { ?s a [] } } } `

So my question is if this query can be optimized in any way?

Cheers!

**Comment by timhaynesopenlink** [comment]
Hi,

I don't know about runtime performance optimization, but it could certainly be written more elegantly:

```
select ?s ?p ?o  { ?s a ?class; ?p ?o . }
```

Note how `?class` is used but not returned.

I'd be interested to hear about relative performance as well.

HTH

**Comment by TallTed** [comment]
It's not clear what data is being assumed, in this presentation. It is helpful to use Turtle notation for sample data and sample results.

If I understand your question correctly, you want to get full descriptions of every entity which has an `rdf:type` property.  You might try something like

```sparql
SELECT ?s ?p ?o 
WHERE
 { ?s ?p ?o . 
   OPTIONAL { ?s a ?type } .
   FILTER ( BOUND ( ?type ) ) 
 }
```

That returns very quickly on [DBpedia](http://dbpedia.org/sparql?default-graph-uri=http%3A%2F%2Fdbpedia.org&qtxt=SELECT+%3Fs+%3Fp+%3Fo+%0D%0AWHERE%0D%0A+%7B+%3Fs+%3Fp+%3Fo+.+%0D%0A+++OPTIONAL+%7B+%3Fs+a+%3Ftype+%7D+.%0D%0A+++FILTER+%28+BOUND+%28+%3Ftype+%29+%29+%0D%0A+%7D%0D%0A&format=text%2Fhtml&CXML_redir_for_subjs=121&CXML_redir_for_hrefs=&timeout=30000&debug=on&run=+Run+Query+) and the [LOD Cloud Cache](http://lod.openlinksw.com/sparql?default-graph-uri=&qtxt=SELECT+%3Fs+%3Fp+%3Fo+%0D%0AWHERE%0D%0A+%7B+%3Fs+%3Fp+%3Fo+.+%0D%0A+++OPTIONAL+%7B+%3Fs+a+%3Ftype+%7D+.%0D%0A+++FILTER+%28+BOUND+%28+%3Ftype+%29+%29+%0D%0A+%7D%0D%0A&format=text%2Fhtml&timeout=30000&debug=on&run=+Run+Query+).

Adding `ORDER BY ASC ( ?s )` slows the return a lot, but may be helpful to you.

**Comment by SteffRhes** [comment]
@timhaynesopenlink  This query we tried out at first but it produces unwanted triples when there are similar triples (but connected to different graphs). e.g. assume the nquad:
```
<s1>    a      <t1>    <g1> .
<s1>    a      <t2>    <g1> .
<s1>    <p>    <o1>    <g1> .
<s2>    <p>    <o2>    <g1> .
```
that query 
`select ?s ?p ?o ?g { graph ?g { ?s a ?class; ?p ?o . } }`
returns:
```
?s    ?p                                                 ?o    ?g
s1    http://www.w3.org/1999/02/22-rdf-syntax-ns#type    t2    g1
s1    http://www.w3.org/1999/02/22-rdf-syntax-ns#type    t2    g1
s1    http://www.w3.org/1999/02/22-rdf-syntax-ns#type    t1    g1
s1    http://www.w3.org/1999/02/22-rdf-syntax-ns#type    t1    g1
s1    p                                                  o1    g1
s1    p                                                  o1    g1
```
This is some behavior of sparql which I found very confusing at first anyway, and as far as I interpret it is due to substitution of variables with values from one part in the where clause into the other part. 
So to avoid that we wrote the query as stated here initially.

**Comment by SteffRhes** [comment]
@TallTed thanks for your input, but unfortunately on the test data set your query returns 2330 rows while mine returns 2327. 
I'll look into those different rows and try to understand your query and also the reason behind the different results and will comment it here once I found out.

**Comment by TallTed** [comment]
Generic placeholder data is often difficult to work with, especially when trying to understand how SPARQL works (which is *related* to, but very much *not the same* as SQL).

I encourage you to conduct these experiments against live data that we can also see, such as [DBpedia](http://dbpedia.org/sparql), the [LOD Cloud Cache](http://lod.openlinksw.com/sparql), or [URIBurner](http://linkeddata.uriburner.com/sparql).

**Comment by timhaynesopenlink** [comment]
Hi,

Your output and query do not match. You've said a query involving `?s` `?p` `?o` `?g` but you list `?class` in the result. 

As with SQL, if there are variables used in the pattern selections and omitted in the output fields, duplication will occur - think "`distinct` _`over`_ `?g`". 

My query as stated will give all the triples about entities that have a defined type. That includes the type as well, just not as a separate field -- the pattern ```{?s ?p ?o}``` will match the case where `?p==rdf:type`.
TallTed's query is similar -- I'm thinking the idea of `optional`+`bound` might provide an extra hint to the optimizer that the `?type` is not a required output field.

If you need to filter it down further by graph, how about:

```
select ?s ?p ?o from <g1> from <g2> ...... from <g3>  { ?s a ?class; ?p ?o . }
```
?

HTH

**Comment by SteffRhes** [comment]
@timhaynesopenlink : Oops, I had that edited manually before to resemble your statement. Now I've corrected it, and also executed that query exactly like it is on the small test data set, leading to the same results though. 

Also to be sure I ran another try:

test data as nquad:
```
<s1>	a	<t1>	<g1> .
<s1>	a	<t2>	<g1> .
<s1>	<p>	<o1>	<g1> .
<s2>	<p>	<o2>	<g1> .

```
I've altered the query again to : 
` select ?s ?p ?o ?class ?g { graph ?g { ?s a ?class; ?p ?o . } }`
to be sure to also output the `?class` variable which is used in the pattern selection, but the result still contains duplicates: 
```
| ?s | ?p                                              | ?o | ?class | ?g |
|----|-------------------------------------------------|----|--------|----|
| s1 | http://www.w3.org/1999/02/22-rdf-syntax-ns#type | t2 | t1     | g1 |
| s1 | http://www.w3.org/1999/02/22-rdf-syntax-ns#type | t2 | t2     | g1 |
| s1 | http://www.w3.org/1999/02/22-rdf-syntax-ns#type | t1 | t1     | g1 |
| s1 | http://www.w3.org/1999/02/22-rdf-syntax-ns#type | t1 | t2     | g1 |
| s1 | p                                               | o1 | t1     | g1 |
| s1 | p                                               | o1 | t2     | g1 |
```

Unfortunately restricting for the graphs manually inside the query as you have suggested is out of question because we are actually aggregating heterogeneous data sets wherein many have their own graphs attached, resulting in ~50k graphs in our virtuoso instance.

@TallTed Yeah, I'm more experienced in SQL and had to get used to the differences to SPARQL first in order to grasp its usages.

But now as you suggested to run on mutual test data, I ran a few queries on http://dbpedia.org/sparql with their results attached. The queries are all additionally restricted to `<http://dbpedia.org/resource/Treaty_of_Bern>` as subject since otherwise some queries timed out:

```
select count(*) where { 
?s ?p ?o .
VALUES ?s {<http://dbpedia.org/resource/Treaty_of_Bern>} 
}
```
returns 533


```
select count(*) where { 
?s a ?class ; 
?p ?o .
VALUES ?s {<http://dbpedia.org/resource/Treaty_of_Bern>} 
}
```
returns 136981


```
select count(*) where { 
?s ?p ?o
OPTIONAL { ?s a ?type } .
FILTER ( BOUND ( ?type ) ) .
VALUES ?s {<http://dbpedia.org/resource/Treaty_of_Bern>} 
}
```
returns 136981

```
select count(*) where { 
?s ?p ?o .
{ 
  select distinct (?s) where {
  ?s a [] } 
} .
VALUES ?s {<http://dbpedia.org/resource/Treaty_of_Bern>} 
}
```
returns 533

So speaking from those queries it still seems that my original one produces the desired result. Or do I miss something / misinterpreted your queries?

Cheers!

PS: I'm leaving work now and will come back again tomorrow should you reply and wonder why I'd stay silent.

**Comment by TallTed** [comment]
First off, your latest SPARQL query result in reply to @timhaynesopenlink  contains no duplicates -- each row is unique (this is easily seen, if you focus on the `?o` and `?class` columns).  If some of the columns in this result set are not important to you, then remove them from your `SELECT` clause.  You can also change your query to `SELECT DISTINCT` to make Virtuoso ensure that each row is unique.

To the other reported results, due to some particular dirtiness in the static DBpedia data (many things, including the [Treaty of Bern](http://dbpedia.org/resource/Treaty_of_Bern), are incorrectly classed as `dbo:person`).  I suggest switching these queries to run instead on [DBpedia-Live](http://live.dbpedia.org/sparql).  The counts on your queries drop from 533 to 299, and from 136981 to 9867.

That said, your versions of my queries are indeed problematic -- because the `OPTIONAL` clause introduces an extra column, so when you do `SELECT *` you get a Cartesian product, multiplying the number of `?s ?p ?o` rows (299) by the number of `rdf:type`/`a` rows (33), for a total of -- **9867**, matching the `COUNT` on your versions of my queries.  If you instead do the `SELECT ?s ?p ?o` which I suggested above, you get the same 299 rows back, as you do in your first and last queries.

To be clear -- [my recommended query](http://live.dbpedia.org/sparql?default-graph-uri=http%3A%2F%2Fdbpedia.org&qtxt=SELECT+%0D%0A+++DISTINCT++%3Fs+%3Fp+%3Fo+%0D%0AWHERE%0D%0A++%7B+%0D%0A++++VALUES+%3Fs+%7B+%3Chttp%3A%2F%2Fdbpedia.org%2Fresource%2FTreaty_of_Bern%3E+%7D+%0D%0A++++%3Fs+%3Fp+%3Fo%0D%0A++++OPTIONAL+%7B+%3Fs+a+%3Ftype+%7D+.%0D%0A++++FILTER+%28+BOUND+%28+%3Ftype+%29+%29+.%0D%0A++%7D%0D%0A&format=text%2Fhtml&CXML_redir_for_subjs=121&CXML_redir_for_hrefs=&timeout=30000&signal_void=on&signal_unconnected=on&run=+Run+Query+) (with your `VALUES` clause) --

```SPARQL
SELECT 
   DISTINCT  ?s ?p ?o 
WHERE
  { 
    VALUES ?s { <http://dbpedia.org/resource/Treaty_of_Bern> } 
    ?s ?p ?o
    OPTIONAL { ?s a ?type } .
    FILTER ( BOUND ( ?type ) ) .
  }
```
-- and the necessary wraparound to [get a count of those results](http://live.dbpedia.org/sparql?default-graph-uri=http%3A%2F%2Fdbpedia.org&qtxt=SELECT+%0D%0A+++%28+COUNT%28+*+%29+AS+%3FHowManyTriples+%29%0D%0AWHERE%0D%0A++%7B+%0D%0A++++%7B+SELECT+%0D%0A+++++++++DISTINCT++%3Fs+%3Fp+%3Fo+%0D%0A++++++WHERE%0D%0A+++++++%7B+%0D%0A+++++++++VALUES+%3Fs+%7B+%3Chttp%3A%2F%2Fdbpedia.org%2Fresource%2FTreaty_of_Bern%3E+%7D+%0D%0A+++++++++%3Fs+%3Fp+%3Fo%0D%0A+++++++++OPTIONAL+%7B+%3Fs+a+%3Ftype+%7D+.%0D%0A+++++++++FILTER+%28+BOUND+%28+%3Ftype+%29+%29+.%0D%0A+++++++%7D%0D%0A++++%7D%0D%0A++%7D%0D%0A%0D%0A%0D%0A&format=text%2Fhtml&CXML_redir_for_subjs=121&CXML_redir_for_hrefs=&timeout=30000&signal_void=on&signal_unconnected=on&run=+Run+Query+) (because SPARQL 1.1 doesn't permit a count of multiple columns unless it's `*`, and that delivers the Cartesian count) --

```SPARQL
SELECT 
  ( COUNT( * ) AS ?HowManyTriples )
WHERE
  { 
    { 
      SELECT 
        DISTINCT  ?s ?p ?o 
      WHERE
       { 
         VALUES ?s { <http://dbpedia.org/resource/Treaty_of_Bern> } 
         ?s ?p ?o
         OPTIONAL { ?s a ?type } .
         FILTER ( BOUND ( ?type ) ) .
       }
    }
  }
```

**Comment by SteffRhes** [comment]
Ah, well, you're right, there is indeed no duplicates in the exhaustive result of the query by @timhaynesopenlink. But on the other hand two subsets still contain duplicates, i.e. looking only at `?s ?p ?o` or `?s ?p ?class` triples, which are essentially those though I'm interested in as an end-result. 
Also simply removing `?class` still results in duplicated `?s ?p ?o ` triples as detailed in my second comment , but yeah, using `select distinct` works indeed.

Besides that though, the queries you've provided now also produce the desired result. I'm currently testing them and others to compare their performance and will update the results here once available.

Generally thanks for your detailed explanation, it did clear up a few uncertainties I've had about sparql.
