### ISSUE TITLE
Nested Query performance 

### ISSUE THREAD

**Issue by aishahasmoh** [openlink/virtuoso-opensource#769]
# Nested query performance on Virtuoso

## Introduction
I am using `isql-vt` to query my local OpenLink Virtuoso server. 

### Twittter graph query

I am trying to run a query on a Twitter graph to find the tweets of tweeters who have only 250-300 tweets. Specifically I am trying to find the (content, tweeter, hashtags, mentions, and URIs) in the tweets of the tweeters who have 250-300 tweets. I ran into a performance issue that I will report here.

As twitter graph is not very well known, I replicated the same issue on the DBpedia dataset. I let _places of birth_ replace _tweeters_ and _people born in a place_ replace the _tweets of the tweeter_.

### DBpedia query

In this query, I am trying to find the (name, place of birth, optionally date of birth and date of death) for every instance that has a date of birth. The only condition that I have is I only want people who were born in places such that only _250 to 300_ people in DBpedia where born in that place. 

I am using a nested query to do it. 

- The inner query finds all the _places of birth_ such that the number of people who were born in that place are 250-300. 
- The outer query finds (name, place of birth, optionally date of birth and date of death) of all instances of all people in dbpedia. 
- The join implemented by the nested query filters these people to include only those whose place of birth is one of the places returned by the inner query. 

The implementation of the queries is included at the end of this report. 

The problem is the huge degradation of performance once I use the nested query.
- The inner query returns 137 Rows in 3.865 sec.
- The outer query returns 3,976,703 Rows in 253.890 sec = 4.2315 min
- The nested query returns 79640 Rows in 10623.9 sec = 177.1 min = 2.95 hour

My questions are: 
1. Can you explain what causes this degradation of performance when using the nested queries?
2. Is there a way to improve Virtuoso performance on nested queries?
3. Is there a way to rewrite this query in SPARQL to be faster?

### Inner query
```sparql
PREFIX  :     <http://dbpedia.org/resource/>
PREFIX  dbo:  <http://dbpedia.org/ontology/>
PREFIX  dbp:  <http://dbpedia.org/property/>

SELECT ?place
WHERE
{
  GRAPH <http://dbpedia.org/>
  {  
    ?person  dbo:birthPlace  ?place 
  } 
}
GROUP BY ?place 
HAVING ((count(?person) < 300) && (count(?person) > 250)) 
ORDER BY ?place
```

### Outer query
```sparql
PREFIX  :     <http://dbpedia.org/resource/>
PREFIX  dbo:  <http://dbpedia.org/ontology/>
PREFIX  dbp:  <http://dbpedia.org/property/>
PREFIX  foaf: <http://xmlns.com/foaf/0.1/>

SELECT ?name, ?place , ?birth, ?death 
WHERE
{ 
  GRAPH <http://dbpedia.org/>
  { 
    ?person dbo:birthPlace  ?place ;
             foaf:name       ?name .
    OPTIONAL 
    {
      ?person dbo:birthDate   ?birth ;
              dbo:deathDate   ?death     
    }        
  }
}
ORDER BY ?place
```

### Nested query
```sparql
PREFIX  :     <http://dbpedia.org/resource/>
PREFIX  dbo:  <http://dbpedia.org/ontology/>
PREFIX  dbp:  <http://dbpedia.org/property/>
PREFIX  foaf: <http://xmlns.com/foaf/0.1/>

SELECT ?name, ?place ,?birth, ?death 
WHERE
{ 
  GRAPH <http://dbpedia.org/>
  {  
    ?person  dbo:birthPlace  ?place ;
             foaf:name       ?name .
    OPTIONAL 
    {
      ?person dbo:birthDate   ?birth ;
              dbo:deathDate   ?death
    }
    {
      SELECT ?place
      WHERE
      {
        GRAPH <http://dbpedia.org/>
        {  
          ?person  dbo:birthPlace  ?place 
        }
      } 
      GROUP BY ?place 
      HAVING ((count(?person) < 300) && (count(?person) > 250)) 
      ORDER BY ?place
    }       
  }
}
ORDER BY ?place
```

**Comment by timhaynesopenlink** [comment]
Hi,
Just a quick thought: the data is quite duplicated. 
Just picking a random person, see http://dbpedia.org/page/Abraham_Robinson
All dates doubled-up, 2 birthplaces, 3 death places. 
There may be much better solutions overall, but as a suggestion: if you can add a `distinct` somewhere in the middle there, it might make life a bit faster.

HTH

**Comment by TallTed** [comment]
0. First thing, the software you're running is named **OpenLink Virtuoso**, or more properly, the **Virtuoso Universal Server from OpenLink Software** (not "virtuoso open-link").

1. Next, am I correct in thinking that your reproduction with the DBpedia dataset was performed on your own local Virtuoso instance?  I would like to check the version of this instance, as revealed by one of the following commands --

       virtuoso-t -?          # for the Open Source Edition

       virtuoso-iodbc-t -?    # for the Enterprise Edition

   I would like to also check the [performance tuning](http://vos.openlinksw.com/owiki/wiki/VOS/VirtRDFPerformanceTuning), so please provide the `NumberOfBuffers` and `MaxDirtyBuffers` values that are set in your INI file, and the amount of RAM available for Virtuoso.

2. I made several small modifications, including --
   - removing the commas from the `SELECT` (which are not valid in SPARQL)
   - adding the `DISTINCT` (as suggested by @timhaynesopenlink, though this will usually slow the final result delivery)
   - removing the unnecessary `ORDER BY` from the inner query
   - removing the unnecessary `GRAPH` clauses for this endpoint

   Then I ran [my version of your query](http://dbpedia.org/sparql?default-graph-uri=http%3A%2F%2Fdbpedia.org&qtxt=PREFIX++%3A+++++%3Chttp%3A%2F%2Fdbpedia.org%2Fresource%2F%3E%0D%0APREFIX++dbo%3A++%3Chttp%3A%2F%2Fdbpedia.org%2Fontology%2F%3E%0D%0APREFIX++dbp%3A++%3Chttp%3A%2F%2Fdbpedia.org%2Fproperty%2F%3E%0D%0APREFIX++foaf%3A+%3Chttp%3A%2F%2Fxmlns.com%2Ffoaf%2F0.1%2F%3E%0D%0A%0D%0A%23SELECT+%3Fname%2C+%3Fplace+%2C%3Fbirth%2C+%3Fdeath+%0D%0ASELECT+DISTINCT++%3Fname++%3Fplace++%3Fbirth++%3Fdeath+%0D%0AWHERE%0D%0A%7B+%0D%0A%23++GRAPH+%3Chttp%3A%2F%2Fdbpedia.org%2F%3E%0D%0A%23++%7B++%0D%0A++++%3Fperson++dbo%3AbirthPlace++%3Fplace+%3B%0D%0A+++++++++++++foaf%3Aname+++++++%3Fname+.%0D%0A++++OPTIONAL+%0D%0A++++%7B%0D%0A++++++%3Fperson+dbo%3AbirthDate+++%3Fbirth+%3B%0D%0A++++++++++++++dbo%3AdeathDate+++%3Fdeath%0D%0A++++%7D%0D%0A++++%7B%0D%0A++++++SELECT+%3Fplace%0D%0A++++++WHERE%0D%0A++++++%7B%0D%0A%23++++++++GRAPH+%3Chttp%3A%2F%2Fdbpedia.org%2F%3E%0D%0A%23++++++++%7B++%0D%0A++++++++++%3Fperson++dbo%3AbirthPlace++%3Fplace+%0D%0A%23++++++++%7D%0D%0A++++++%7D+%0D%0A++++++GROUP+BY+%3Fplace+%0D%0A++++++HAVING+%28%28count%28%3Fperson%29+%3C+300%29+%26%26+%28count%28%3Fperson%29+%3E+250%29%29+%0D%0A%23++++++ORDER+BY+%3Fplace%0D%0A++++%7D+++++++%0D%0A%23++%7D%0D%0A%7D%0D%0AORDER+BY+%3Fplace%0D%0A&format=text%2Fhtml&CXML_redir_for_subjs=121&CXML_redir_for_hrefs=&timeout=30000&debug=on&run=+Run+Query+) on the public DBpedia endpoint.  I very quickly got back [the maximum 10,000 rows](http://dbpedia.org/sparql?default-graph-uri=http%3A%2F%2Fdbpedia.org&query=PREFIX++%3A+++++%3Chttp%3A%2F%2Fdbpedia.org%2Fresource%2F%3E%0D%0APREFIX++dbo%3A++%3Chttp%3A%2F%2Fdbpedia.org%2Fontology%2F%3E%0D%0APREFIX++dbp%3A++%3Chttp%3A%2F%2Fdbpedia.org%2Fproperty%2F%3E%0D%0APREFIX++foaf%3A+%3Chttp%3A%2F%2Fxmlns.com%2Ffoaf%2F0.1%2F%3E%0D%0A%0D%0A%23SELECT+%3Fname%2C+%3Fplace+%2C%3Fbirth%2C+%3Fdeath+%0D%0ASELECT+DISTINCT++%3Fname++%3Fplace++%3Fbirth++%3Fdeath+%0D%0AWHERE%0D%0A%7B+%0D%0A%23++GRAPH+%3Chttp%3A%2F%2Fdbpedia.org%2F%3E%0D%0A%23++%7B++%0D%0A++++%3Fperson++dbo%3AbirthPlace++%3Fplace+%3B%0D%0A+++++++++++++foaf%3Aname+++++++%3Fname+.%0D%0A++++OPTIONAL+%0D%0A++++%7B%0D%0A++++++%3Fperson+dbo%3AbirthDate+++%3Fbirth+%3B%0D%0A++++++++++++++dbo%3AdeathDate+++%3Fdeath%0D%0A++++%7D%0D%0A++++%7B%0D%0A++++++SELECT+%3Fplace%0D%0A++++++WHERE%0D%0A++++++%7B%0D%0A%23++++++++GRAPH+%3Chttp%3A%2F%2Fdbpedia.org%2F%3E%0D%0A%23++++++++%7B++%0D%0A++++++++++%3Fperson++dbo%3AbirthPlace++%3Fplace+%0D%0A%23++++++++%7D%0D%0A++++++%7D+%0D%0A++++++GROUP+BY+%3Fplace+%0D%0A++++++HAVING+%28%28count%28%3Fperson%29+%3C+300%29+%26%26+%28count%28%3Fperson%29+%3E+250%29%29+%0D%0A%23++++++ORDER+BY+%3Fplace%0D%0A++++%7D+++++++%0D%0A%23++%7D%0D%0A%7D%0D%0AORDER+BY+%3Fplace%0D%0A&format=text%2Fhtml&CXML_redir_for_subjs=121&CXML_redir_for_hrefs=&timeout=30000&debug=on&run=+Run+Query+).  (Note that there are multiple forms of birthdate and deathdate, which often lead to multiple rows for a single person.)

4. [Another small modification](http://dbpedia.org/sparql?default-graph-uri=http%3A%2F%2Fdbpedia.org&qtxt=PREFIX++%3A+++++%3Chttp%3A%2F%2Fdbpedia.org%2Fresource%2F%3E%0D%0APREFIX++dbo%3A++%3Chttp%3A%2F%2Fdbpedia.org%2Fontology%2F%3E%0D%0APREFIX++dbp%3A++%3Chttp%3A%2F%2Fdbpedia.org%2Fproperty%2F%3E%0D%0APREFIX++foaf%3A+%3Chttp%3A%2F%2Fxmlns.com%2Ffoaf%2F0.1%2F%3E%0D%0A%0D%0ASELECT+%28COUNT%28*%29+AS+%3Fcount%29+%7B%0D%0A%0D%0ASELECT+DISTINCT+%3Fname+%3Fplace+%3Fbirth+%3Fdeath%0D%0AWHERE%0D%0A%7B+%0D%0A++++%3Fperson++dbo%3AbirthPlace++%3Fplace+%3B%0D%0A+++++++++++++foaf%3Aname+++++++%3Fname+.%0D%0A++++OPTIONAL+%0D%0A++++%7B%0D%0A++++++%3Fperson+dbo%3AbirthDate+++%3Fbirth+%3B%0D%0A++++++++++++++dbo%3AdeathDate+++%3Fdeath%0D%0A++++%7D%0D%0A++++%7B%0D%0A++++++SELECT+%3Fplace%0D%0A++++++WHERE%0D%0A++++++++%7B++%0D%0A++++++++++%3Fperson++dbo%3AbirthPlace++%3Fplace+%0D%0A++++++++%7D%0D%0A++++++GROUP+BY+%3Fplace+%0D%0A++++++HAVING+%28%28count%28%3Fperson%29+%3C+300%29+%26%26+%28count%28%3Fperson%29+%3E+250%29%29+%0D%0A%23++++++ORDER+BY+%3Fplace%0D%0A++++%7D+++++++%0D%0A%7D%0D%0AORDER+BY+%3Fplace%0D%0A%7D&format=text%2Fhtml&CXML_redir_for_subjs=121&CXML_redir_for_hrefs=&timeout=3000000&debug=on&run=+Run+Query+), and within 10 seconds, I found that the [total rows would be under 60,000](http://dbpedia.org/sparql?default-graph-uri=http%3A%2F%2Fdbpedia.org&query=PREFIX++%3A+++++%3Chttp%3A%2F%2Fdbpedia.org%2Fresource%2F%3E%0D%0APREFIX++dbo%3A++%3Chttp%3A%2F%2Fdbpedia.org%2Fontology%2F%3E%0D%0APREFIX++dbp%3A++%3Chttp%3A%2F%2Fdbpedia.org%2Fproperty%2F%3E%0D%0APREFIX++foaf%3A+%3Chttp%3A%2F%2Fxmlns.com%2Ffoaf%2F0.1%2F%3E%0D%0A%0D%0ASELECT+%28COUNT%28*%29+AS+%3Fcount%29+%7B%0D%0A%0D%0ASELECT+DISTINCT+%3Fname+%3Fplace+%3Fbirth+%3Fdeath%0D%0AWHERE%0D%0A%7B+%0D%0A++++%3Fperson++dbo%3AbirthPlace++%3Fplace+%3B%0D%0A+++++++++++++foaf%3Aname+++++++%3Fname+.%0D%0A++++OPTIONAL+%0D%0A++++%7B%0D%0A++++++%3Fperson+dbo%3AbirthDate+++%3Fbirth+%3B%0D%0A++++++++++++++dbo%3AdeathDate+++%3Fdeath%0D%0A++++%7D%0D%0A++++%7B%0D%0A++++++SELECT+%3Fplace%0D%0A++++++WHERE%0D%0A++++++++%7B++%0D%0A++++++++++%3Fperson++dbo%3AbirthPlace++%3Fplace+%0D%0A++++++++%7D%0D%0A++++++GROUP+BY+%3Fplace+%0D%0A++++++HAVING+%28%28count%28%3Fperson%29+%3C+300%29+%26%26+%28count%28%3Fperson%29+%3E+250%29%29+%0D%0A%23++++++ORDER+BY+%3Fplace%0D%0A++++%7D+++++++%0D%0A%7D%0D%0AORDER+BY+%3Fplace%0D%0A%7D&format=text%2Fhtml&CXML_redir_for_subjs=121&CXML_redir_for_hrefs=&timeout=3000000&debug=on&run=+Run+Query+).


I hope this is helpful.

**Comment by aishahasmoh** [comment]
Thank you for your response. It is very helpful.

1. Yes I am running it on my local virtuoso server. 

   The version of the instance as revealed by the `virtuoso-t -?` command is:
   ```
   Virtuoso Open Source Edition (multi threaded)
   Version 6.1.6.3127-pthreads as of Sep 24 2013
   Compiled for Linux (x86_64-pc-linux-gnu)
   Copyright (C) 1998-2012 OpenLink Software
   ```
   In my INI file:  
   ```
   NumberOfBuffers          = 19000000
   MaxDirtyBuffers          = 15000000
   ```
   The amount of RAM available as revealed by `cat /proc/meminfo` command is:
   ```
   MemTotal:       264109248 kB
   MemFree:        18820432 kB
   ```

2. When I run your query on my machine without adding `DISTINCT`, I get the same 79640 Rows I got before in 7.844 sec. Which means removing the  `GRAPH` statement makes it that much faster on my machine. It went from ~3 hours to 7.844 sec.

   Do you know why does adding the `GRAPH` statement degrade the performance that badly though its supposed to improve the performance.

3. Does adding `Distinct` here makes sure there is only one row for each name? or one row for each person? what if 2 people have the same name?

4. I tried the exact same modifications on the twitter graph query but it didn't improve the performance at all. Here is my query for the twitter graph. Can you help me figure out how to improve the performance?
   ```sparql
   PREFIX  :     <http://twitter.com/>
   PREFIX  sioc: <http://rdfs.org/sioc/ns#>
   PREFIX  sto:  <https://w3id.org/i40/sto#>

   SELECT  ?text ?twitter ?hashtag ?mentions
   WHERE
     { ?tweet  sioc:has_creator  ?twitter ;
               sioc:content      ?text
       OPTIONAL
         { ?tweet  sto:hasTag     ?hashtag ;
                   sioc:mentions  ?mentions 
         }
       { SELECT  ?twitter
         WHERE
           { ?tweet  sioc:has_creator  ?twitter }
         GROUP BY ?twitter
         HAVING ( ( COUNT(?tweet) < 300 ) && ( COUNT(?tweet) > 250 ) )
       }
     }
   ORDER BY ?twitter
   ```

**Comment by TallTed** [comment]
OK...

1. Please note that Virtuoso 6.1 hasn't been updated since [6.1.8 of December 2013](http://vos.openlinksw.com/owiki/wiki/VOS/VOSNews2013#2013-12-10%20--%20Virtuoso%20Open-Source%20Edition%206.1.8%20Released) -- which is still more than a year younger/better than the [6.1.6 of August 2012 (though built in September 2013)](http://vos.openlinksw.com/owiki/wiki/VOS/VOSNews2012#2012-08-02%20--%20Announcing%20Virtuoso%20Open-Source%20Edition%20v6.1.6) you're running.  There have been dozens if not hundreds of changes since then, including bugfixes, performance boosts, and feature enhancements.

   My first suggestion is therefore to [upgrade your instance](http://vos.openlinksw.com/owiki/wiki/VOS/UpgradingToVOS610#Upgrading%20from%20Release%206.x%20to%20Release%207.x) to the just released [`stable/7`, v7.2.5.1](https://github.com/openlink/virtuoso-opensource/tree/stable/7). If (and only if) you absolutely cannot upgrade to v7, then [update your instance](http://vos.openlinksw.com/owiki/wiki/VOS/UpgradingToVOS610#Upgrading%20from%20Release%206.1.x%20to%20a%20newer%20Release%206.1.x) to the latest v6, [6.1.8](http://vos.openlinksw.com/owiki/wiki/VOS/VOSNews2013#2013-12-10%20--%20Virtuoso%20Open-Source%20Edition%206.1.8%20Released).

   Regarding memory settings -- did you run `cat /proc/meminfo` while Virtuoso was running, or while it was stopped?  If while it was running, please stop Virtuoso, repeat the command, and provide the new output.  

   If while it was stopped, please note that this means that while your machine has 256GB RAM, less than 18GB is available to Virtuoso.  Therefore, please change your INI file settings to --
   ```
   NumberOfBuffers = 1589950  ; =~ 18820432 * 1024 * .66 / 8000
   MaxDirtyBuffers = 1192462  ; =~ 1589950 * .75
   ```

2. Regarding performance impact of the `GRAPH` clause -- I don't know why you're seeing the difference you are.  I just [put those back (and removed the query form's Default Graph setting)](http://dbpedia.org/sparql?default-graph-uri=&qtxt=PREFIX++%3A+++++%3Chttp%3A%2F%2Fdbpedia.org%2Fresource%2F%3E%0D%0APREFIX++dbo%3A++%3Chttp%3A%2F%2Fdbpedia.org%2Fontology%2F%3E%0D%0APREFIX++dbp%3A++%3Chttp%3A%2F%2Fdbpedia.org%2Fproperty%2F%3E%0D%0APREFIX++foaf%3A+%3Chttp%3A%2F%2Fxmlns.com%2Ffoaf%2F0.1%2F%3E%0D%0A%0D%0A%23SELECT+%3Fname%2C+%3Fplace+%2C%3Fbirth%2C+%3Fdeath+%0D%0ASELECT+DISTINCT++%3Fname++%3Fplace++%3Fbirth++%3Fdeath+%0D%0AWHERE%0D%0A%7B+%0D%0A++GRAPH+%3Chttp%3A%2F%2Fdbpedia.org%3E%0D%0A++%7B++%0D%0A++++%3Fperson++dbo%3AbirthPlace++%3Fplace+%3B%0D%0A+++++++++++++foaf%3Aname+++++++%3Fname+.%0D%0A++++OPTIONAL+%0D%0A++++%7B%0D%0A++++++%3Fperson+dbo%3AbirthDate+++%3Fbirth+%3B%0D%0A++++++++++++++dbo%3AdeathDate+++%3Fdeath%0D%0A++++%7D%0D%0A++++%7B%0D%0A++++++SELECT+%3Fplace%0D%0A++++++WHERE%0D%0A++++++%7B%0D%0A++++++++GRAPH+%3Chttp%3A%2F%2Fdbpedia.org%3E%0D%0A++++++++%7B++%0D%0A++++++++++%3Fperson++dbo%3AbirthPlace++%3Fplace+%0D%0A++++++++%7D%0D%0A++++++%7D+%0D%0A++++++GROUP+BY+%3Fplace+%0D%0A++++++HAVING+%28%28count%28%3Fperson%29+%3C+300%29+%26%26+%28count%28%3Fperson%29+%3E+250%29%29+%0D%0A%23++++++ORDER+BY+%3Fplace%0D%0A++++%7D+++++++%0D%0A++%7D%0D%0A%7D%0D%0AORDER+BY+%3Fplace%0D%0A&format=text%2Fhtml&CXML_redir_for_subjs=121&CXML_redir_for_hrefs=&timeout=3000000&debug=on&run=+Run+Query+) and retested on the live DBpedia endpoint, and again, [response was quite quick](http://dbpedia.org/sparql?default-graph-uri=&query=PREFIX++%3A+++++%3Chttp%3A%2F%2Fdbpedia.org%2Fresource%2F%3E%0D%0APREFIX++dbo%3A++%3Chttp%3A%2F%2Fdbpedia.org%2Fontology%2F%3E%0D%0APREFIX++dbp%3A++%3Chttp%3A%2F%2Fdbpedia.org%2Fproperty%2F%3E%0D%0APREFIX++foaf%3A+%3Chttp%3A%2F%2Fxmlns.com%2Ffoaf%2F0.1%2F%3E%0D%0A%0D%0A%23SELECT+%3Fname%2C+%3Fplace+%2C%3Fbirth%2C+%3Fdeath+%0D%0ASELECT+DISTINCT++%3Fname++%3Fplace++%3Fbirth++%3Fdeath+%0D%0AWHERE%0D%0A%7B+%0D%0A++GRAPH+%3Chttp%3A%2F%2Fdbpedia.org%3E%0D%0A++%7B++%0D%0A++++%3Fperson++dbo%3AbirthPlace++%3Fplace+%3B%0D%0A+++++++++++++foaf%3Aname+++++++%3Fname+.%0D%0A++++OPTIONAL+%0D%0A++++%7B%0D%0A++++++%3Fperson+dbo%3AbirthDate+++%3Fbirth+%3B%0D%0A++++++++++++++dbo%3AdeathDate+++%3Fdeath%0D%0A++++%7D%0D%0A++++%7B%0D%0A++++++SELECT+%3Fplace%0D%0A++++++WHERE%0D%0A++++++%7B%0D%0A++++++++GRAPH+%3Chttp%3A%2F%2Fdbpedia.org%3E%0D%0A++++++++%7B++%0D%0A++++++++++%3Fperson++dbo%3AbirthPlace++%3Fplace+%0D%0A++++++++%7D%0D%0A++++++%7D+%0D%0A++++++GROUP+BY+%3Fplace+%0D%0A++++++HAVING+%28%28count%28%3Fperson%29+%3C+300%29+%26%26+%28count%28%3Fperson%29+%3E+250%29%29+%0D%0A%23++++++ORDER+BY+%3Fplace%0D%0A++++%7D+++++++%0D%0A++%7D%0D%0A%7D%0D%0AORDER+BY+%3Fplace%0D%0A&format=text%2Fhtml&CXML_redir_for_subjs=121&CXML_redir_for_hrefs=&timeout=3000000&debug=on&run=+Run+Query+).  My best immediate guess is -- there was a relevant patch between then and now.

3. `DISTINCT` makes each row unique within the result set.  There may be multiple rows that have the same values in one or more columns, but there will not be multiple rows that have the same values in *all* columns.

4. Is the Twitter data in the same DB file, in the same instance, as the DBpedia data you're testing?  If not, I'd guess the two instances have some different configuration(s) and/or indexing needs to be rebuilt on the Twitter instance.  There may be other differences between the two.

   If the same instance holds all data for both of these graphs, there may be more to dig into ... which should wait until after you upgrade the engine you're using, and we see whether that brings any improvement.

**Comment by TallTed** [comment]
@aishahasmoh - Were you able to act on my latest suggestions?  Did these help?  Please let me know, so we can take appropriate next steps.

**Comment by aishahasmoh** [comment]
Thank you for your response. 
I have been trying to work on it.

First, I shut down virtuoso and checked the memory that I have and it is
```
MemTotal:       264109248 kB
MemFree:        187115264 kB
```
So, I do have around 180GB of RAM available for virtuoso.

Second, Yes my Twitter graph is in the same file on the same instance. 

Third, 
I tried to update to version 7 stable but I faced some errors that I couldn't resolve while trying to update to version 7. I followed the instructions as in the git repo for a 64 bit linux machine. I could build it but when I tried to compile using ```make``` I got the following error:
```
make[2]: Entering directory `/ssd/amohamed/virtuoso-opensource/binsrc/VirtuosoClient.Net'
mcs /unsafe /target:library /out:OpenLink.Data.Virtuoso.dll /sdk:2 /optimize+ /d:MONO /d:ADONET2 ./ArrayOfLongPacked.cs ./AssemblyInfo.cs ./BlobHandle.cs ./BufferType.cs ./CLI.cs ./ConnectionOptions.cs ./ConnectionPool.cs ./ConnectionStringParser.cs ./DataType.cs ./DateTimeMarshaler.cs ./Diagnostics.cs ./DTC.cs ./Era.cs ./ExplicitString.cs ./Future.cs ./FutureList.cs ./IConvertData.cs ./ICreateErrors.cs ./IInnerCommand.cs ./IInnerConnection.cs ./IMarshal.cs ./InnerConnectionBase.cs ./ISession.cs ./IVirtuosoError.cs ./ManagedCommand.cs ./ManagedConnection.cs ./ManagedErrors.cs ./Marshaler.cs ./MD5.cs ./MemoryHandle.cs ./Platform.cs ./RPC.cs ./Service.cs ./SqlXml.cs ./SqlExtendedString.cs ./SqlRdfBox.cs ./TcpConnection.cs ./TcpSession.cs ./Unix.cs ./VirtDbType.cs ./VirtuosoCommandBuilder.cs ./VirtuosoCommand.cs ./VirtuosoConnection.cs ./VirtuosoDataAdapter.cs ./VirtuosoDataReader.cs ./VirtuosoDateTime.cs ./VirtuosoDateTimeOffset.cs ./VirtuosoErrorCollection.cs ./VirtuosoError.cs ./VirtuosoException.cs ./VirtuosoInfoMessage.cs ./VirtuosoParameterCollection.cs ./VirtuosoParameter.cs ./VirtuosoPermissionAttribute.cs ./VirtuosoPermission.cs ./VirtuosoTimeSpan.cs ./VirtuosoTransaction.cs ./VirtuosoWarning.cs ./Win32.cs ./VirtuosoClientFactory.cs ./VirtuosoCodeAccessPermission.cs ./VirtuosoConnectionStringBuilder.cs /r:System.Data /r:System.EnterpriseServices /r:System.Drawing /resource:./OpenLink.Data.VirtuosoClient.VirtuosoConnection.bmp /resource:./OpenLink.Data.VirtuosoClient.VirtuosoCommand.bmp /resource:./OpenLink.Data.VirtuosoClient.VirtuosoDataAdapter.bmp
warning CS8001: SDK path could not be resolved
./AssemblyInfo.cs(66,12): warning CS1699: Use compiler option `keyfile' or appropriate project settings instead of `AssemblyKeyFile' attribute
error CS0006: Metadata file `System.Data' could not be found
error CS0006: Metadata file `System.EnterpriseServices' could not be found
Compilation failed: 2 error(s), 2 warnings
make[2]: *** [OpenLink.Data.Virtuoso.dll] Error 1
make[2]: Leaving directory `/ssd/amohamed/virtuoso-opensource/binsrc/VirtuosoClient.Net'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/ssd/amohamed/virtuoso-opensource/binsrc'
make: *** [all-recursive] Error 1
```
I don't know what are the ``` `System.Data' ``` and the ```System.EnterpriseServices``` ans why they are not found.

Here is my machine info as revealed by ```lscpu``` command:
```
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                48
On-line CPU(s) list:   0-47
Thread(s) per core:    2
Core(s) per socket:    12
Socket(s):             2
```
I found that someone had the same issue before but it was not resolved. I found the other issue here:
https://github.com/openlink/virtuoso-opensource/issues/623

Can you please help me resolve this error?
Thank you

**Comment by aishahasmoh** [comment]
Update: I did download the binary executable of version 7 and it did execute the query on the Twitter Graph in 2.56 sec.
Thanks a lot.
