### ISSUE TITLE
Maximum size for property value (triple object) in Virtuoso — example with property geometry `asWKT`

### ISSUE THREAD

**Issue by rapw3k** [openlink/virtuoso-opensource#776]
I didnt want to mix the issue  https://github.com/openlink/virtuoso-opensource/issues/775.

I have a few features with very large geometry value (`asWKT`) and they are not loaded in Virtuoso using the batch loading `rdf_loader_run();`. NOTE: no error is recorded in `DB.DBA.load_list` after loading finishes.

The issue is most probably because the value is quite large (about 36MB). So, I want to know the max size supported in Virtuoso for the triple object value, or perhaps it is measured in terms of triple size?

See sample file with one triple: https://box.psnc.pl/f/9a4f50a851/?raw=1

**Comment by HughWilliams** [comment]
@rapw3k : I can see the problem with both Virtuoso 8 (commercial) & 7 (open source) ...

The 36MB file contains a single multi-polygon triple:

```
<http://w3id.org/foodie/open/cz/ErosionZone/Geometry/1> <http://www.opengis.net/ont/geosparql#asWKT> "MULTIPOLYGON (((14.118878590000065 48.59125028200003, 14.118873407000024 48.59099229600008, 14.118809678000048 48.590864991000046,
.
.
.
36, 14.080844398000067 49.33484751600008, 14.080948578000061 49.33459643600003)))"^^<http://www.opengis.net/ont/geosparql#wktLiteral> .
```

which on bulk load takes a significant amount of time, reports the load is successful but then no triple is loaded:

```
SQL> ld_dir ('.', 'Erosion-sample.nt', 'erosion');

Done. -- 1 msec.
SQL> select * from load_list;
ll_file                                                                           ll_graph                                                                          ll_state    ll_started           ll_done              ll_host     ll_work_time  ll_error
VARCHAR NOT NULL                                                                  VARCHAR                                                                           INTEGER     TIMESTAMP            TIMESTAMP            INTEGER     INTEGER     VARCHAR
_______________________________________________________________________________

./Erosion-sample.nt                                                               erosion                                                                           0           NULL                 NULL                 NULL        NULL        NULL

1 Rows. -- 0 msec.
SQL> rdf_loader_run();

Done. -- 418215 msec.
SQL> select * from load_list;
ll_file                                                                           ll_graph                                                                          ll_state    ll_started           ll_done              ll_host     ll_work_time  ll_error
VARCHAR NOT NULL                                                                  VARCHAR                                                                           INTEGER     TIMESTAMP            TIMESTAMP            INTEGER     INTEGER     VARCHAR
_______________________________________________________________________________

./Erosion-sample.nt                                                               erosion                                                                           2           2018.9.3 22:6.2 102163000  2018.9.3 22:13.0 311515000  0           NULL        NULL

1 Rows. -- 2 msec.
SQL> sparql select count(*) from <erosion> where {?s ?p ?o};
callret-0
INTEGER
_______________________________________________________________________________

0

1 Rows. -- 2 msec.
SQL>
```

This has been reported to development to look into and determine why it silently fails to load ...

**Comment by HughWilliams** [comment]
Development report that, the limit for RDF object literals is 10M characters and more than that can not be processed at the moment. Increasing the limit would require a completely new design of the RDF core or possibly the database engine itself, which will not be done.

As for the error, it is not seen because Bulk-loader is using [`TTLP()`](https://docs.openlinksw.com/virtuoso/fn_ttlp/) flags `0xff` (or, 255), which mean NO recoverable error (such as length) stop loading with an error, but instead the failed triple is skipped and the rest of the triples if any are processed. If one wants strict loading, then [`TTLP()`](https://docs.openlinksw.com/virtuoso/fn_ttlp/) should be used without flags or with them set appropriately to skip only certain error conditions. 

This example of a [`TTLP()`](https://docs.openlinksw.com/virtuoso/fn_ttlp/) run without flags —
```
ttlp(file_open('Erosion-sample.nt'),'', 'urn:bug:18445');
```
— would give this error —
`*** Error 37000: VD [Virtuoso Server][Vectorized Turtle loader] TURTLE RDF loader, line 1: SP029: TURTLE RDF loader, line 1: The double-quoted string is too long at "MULTIPOLYGON (((1...`
