### ISSUE TITLE
A series of `sizeof` issues?

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [openlink/virtuoso-opensource#784]
Hi all,
There are some `sizeof` issues found by Qihoo360 CodeSafe Team.
Details as bellow:

### 1.Memory Allocation
There are two non-fatal issues about memory allocation, see
https://github.com/openlink/virtuoso-opensource/blob/d76ab20f8cdee8b7660bf1b653fda85d08e5153c/libsrc/util/buildarg.c#L119. Result of `s_realloc`, i.e. `realloc` is converted to `char**`, which is incompatiable with the sizeof operand type `char**`. The same issue arises at line 138.

Given the code below, the operand of sizeof is `int`, the allocated memory type will be `int*`. In the same way, if the operand of sizeof is `char**`, the allocated memory type will be `char***`.
```C++
int *ptr = (int*)malloc(sizeof(int));
```
The operand of sizeof, whether `char*` or `char**`, result in the same program behavior. But use the consistent manner will improve the readability.

### 2.Wrong `sizeof` operand.
There are two fatal issues about the `sizeof` operand.

One is at https://github.com/openlink/virtuoso-opensource/blob/develop/7/libsrc/Dk/Dksesstr.c#L1325. 
```C++
long to_read = MIN (sizeof (buffer), src_n_bytes);
```
The value `sizeof(buffer)` is pointer length, there is no reason to compare `src_n_bytes` to the pointer length. 

One is at https://github.com/openlink/virtuoso-opensource/blob/develop/7/libsrc/Wi/srvcr.c#L2102. 
```C++
memset (opts, 0, sizeof (opts));
```
The value of `sizeof(opts)` is pointer length and there is no reason to memset `opts` with pointer length neither.

Can you guys confirm this?

Cheers
Qihoo360 CodeSafe Team

**Comment by IvanMikhailov** [comment]
1. Yes these two should be tweaked.

2. Oops! Our fault. Indeed it's supposed to be `sizeof (src_buffer)` that is a bit bigger than `sizeof (buffer)`, so it was possible to get up to 8000 times more calls of functions inside the loop. E.g. `read_wides_from_utf8_file()` makes it right way.

`memset (opts, 0, sizeof (opts));` is totally redundant, because `opts = ...dk_alloc_box_zero ()` above contains `memzero` already. It's just a happy case  it is not, say, `memset (opts, 0, sizeof (opts[0]));` and it does not overwrite `opts->so_use_bookmarks = 1` above.

Thank you very much for your findings.

**Comment by IvanMikhailov** [comment]
BTW what sort of tool is used to catch these issues, esp. `sizeof (buffer)`?

**Comment by QiAnXinCodeSafe** [comment]
Thank you for your quickly feedback, IvanMikhailov! These issues found by our own symbolic-execution-based static analyzer.

In addition, there is an open source analyzer `clang static analyzer`, see [clang static analyzer][1]. You can write your own checker for these `sizeof(buffer)` cases.
 
[1]: https://github.com/llvm-mirror/clang/tree/master/lib/StaticAnalyzer
