### ISSUE TITLE
What the self-assignment used for?

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [openlink/virtuoso-opensource#785]
Hi all,

There are about 90 self-assignments in `virtuoso-opensource`, they are all located in for-loop, like
https://github.com/openlink/virtuoso-opensource/blob/d76ab20f8cdee8b7660bf1b653fda85d08e5153c/libsrc/Wi/chash.c#L1681.

Self-assignment is useless, and compiler is most likely optimize it away. So I want to know what the self-assignment used for here?

Thanks in advance!

**Comment by IvanMikhailov** [comment]
That's after text macroprocessor. As you may see, all those loops have similar structure: first there are runs grouped in four items; then up to three last items are in short non-grouped loop. There were a series of experiments with different sizes of groups, etc., all made from one source but with different macroexpansion; the benchmark winner is in the source tree. The macroprocessor was not programmed to notice that two parameters were equal in some macro call, so it printed `set = set` instead of empty string. No doubt, compiler wipes away this assignment.

**Comment by QiAnXinCodeSafe** [comment]
Hmm, I see, thanks for your help!

**Comment by TallTed** [comment]
@360CodeSafe - Please close this issue, to confirm that [the above explanation](#issuecomment-423845059) was sufficient for you.
