### ISSUE TITLE
Is it possible to save results from a query and reuse them in a separate query?

### ISSUE THREAD

**Issue by SteffRhes** [openlink/virtuoso-opensource#798]
With Virtuoso, is there some way to temporarily save results from a query and reuse them in a separate query later again? Similar to views in SQL but with temporary persistence and without interfering with the rest of the persisted data?

Probably I could use `CONSTRUCT` and `INSERT` somehow to persist results manually to the store, but if possible I would want to avoid that as I'd prefer this data to not mingle with the other persisted data.

**Comment by TallTed** [comment]
The typical way of achieving this is persistence to a Named Graph, which can be dropped once its utility ends.  Qualifying your queries with `FROM` or `FROM NAMED`, or including `GRAPH <graph-ID>` clauses, is a good way to avoid the sort of "interference" you foresee.

If that doesn't seem viable for your project, perhaps you could provide more detail of what you're trying to do, such that we might offer other suggestions?

**Comment by SteffRhes** [comment]
Ted, thanks for your reply.

The use-case I'm having, is that I want to go traverse big numbers of nodes and edges to map their overall flow. But when doing this in one single query, virtuoso usually times out (and we have already increase the limit to several hours, after which there would be problems with connections anyway) or it puts too much strain on the server overall. Thus I would like to split the traversal into separate queries, each one for each edge hopping step, e.g. start with result set A from whatever query, then find set B of all connected nodes with their relations, form that on to set C and so on until I either hit a self-defined limit of steps or hit the end of connections. Ideally all those sets I can keep in memory and reuse them for the next query.

I'm doing this for biggish graph analysis and want to compress this edge hopping into a bird eye view of quantities of relations and nodes between all these edge hoppings.

So is it possible to cache the result set of nodes into memory and reuse them? 
If not I'll use named graphs then, which I was hoping to avoid for performance and data integrity reasons.

Cheers

**Comment by TallTed** [comment]
@steffres - I wonder first whether your Virtuoso instance is [properly tuned to use local memory](http://vos.openlinksw.com/owiki/wiki/VOS/VirtRDFPerformanceTuning).

I also wonder whether your queries might be optimizable to some degree.  This is very difficult if not impossible to discern from the textual description of what you're trying to do.  Possibly you might try using subqueries -- reverse-stacked because of SPARQL's "bottom-up" evaluation pattern -- which it doesn't appear that you have tried.

Certainly, this pattern of use would benefit from our [latest Enterprise Edition v8.2](https://shop.openlinksw.com/license_generator/virtuoso/?serverVersionSelection=8.2), rather than even the [latest Open Source v7.2.6](https://github.com/openlink/virtuoso-opensource/tree/develop/7).

**Comment by SteffRhes** [comment]
I'm sorry for the absence of replies. We had to shift to other tasks and then this issue was forgotten. I close it now. 

Thanks for your help TallTed.
