### ISSUE TITLE
Update Docker version

### ISSUE THREAD

**Issue by LeoColomb** [openlink/virtuoso-opensource#804]
The Docker images available on the store (https://hub.docker.com/r/openlink/virtuoso_opensource/) seem outdated.
Is it possible to build and add the new versions?

Thanks!

**Comment by TallTed** [comment]
Please take a look at [virtuoso-opensource-7](https://hub.docker.com/r/openlink/virtuoso-opensource-7/), rather than [virtuoso_opensource](https://hub.docker.com/r/openlink/virtuoso_opensource/) (which will likely be removed at some point).

Note that there are a [few images available now](https://hub.docker.com/u/openlink/).

**Comment by LeoColomb** [comment]
Oh nice, didn't catch that! Thanks!
This isn't really documented yet, right?

**Comment by kidehen** [comment]
@LeoColomb ,

The new Docker Containers are documented.

See: https://community.openlinksw.com/tags/docker
