### ISSUE TITLE
Trig in bulkloader gives poor results

### ISSUE THREAD

**Issue by GeraldGrootRoessink** [openlink/virtuoso-opensource#816]
Example 3 from the trig specification is the only one that can be bullkloaded. Partially. This example contains a default graph en two specific ones (Bob and Alice). Bob is loaded, Alice not.  The name of Bob's graph is not used by the bulkloader.

**Comment by TallTed** [comment]
Please confirm -- are you referring to [this TriG spec](https://www.w3.org/TR/trig/), and the examples in the [2.2 Graph Statements](https://www.w3.org/TR/trig/#sec-graph-statements) section?

Please also provide details of how you attempted this bulk load (TriG filenames, Virtuoso host platform, the commands you executed, etc.) and the exact version of Virtuoso in use (output of `virtuoso-iodbc-t -?` or `virtuoso-t -?`).

**Comment by GeraldGrootRoessink** [comment]
Yes, those are the examples. I'm using:

> Virtuoso Open Source Edition (multi threaded)
> Version 7.2.4.3217-threads as of Apr 25 2016
> Compiled for Win64 (x86_64-generic-win-64)

My sequence of actions is this:

* changing `DirsAllowed`-parameter in `virtuoso.ini`: 
  `C:\Program Files (x86)\virtuoso-opensource\database , C:\Program Files (x86)\virtuoso-opensource\vad, C:\Program Files (x86)\virtuoso-opensource\bulkloader`

* in ISQL: 
  `ld_dir_all ('C:/Program Files (x86)/virtuoso-opensource/bulkloader/rio', 'example3.trig', 'http://example.org');`
* in ISQL: 
  `rdf_loader_run();`

I improved the previous result by adding a dot after  the `}`.  Now it loads Alice as well. Still, I expect the triples to be loaded in a graph with the name provided in the trig-file. There's only one graph: `http://example.org`. 

One more curious thing: this graph contains lots of blanks nodes with intermediate results.

Thanks for helping.

**Comment by TallTed** [comment]
My first thought is to suggest that you upgrade from that rather elderly Virtuoso build (from April 2016!) to the current prebuilt `stable/7` ([`7.2.5.1`, built August 2018](https://sourceforge.net/projects/virtuoso/files/virtuoso/7.2.5/Virtuoso_OpenSource_Server_7.20.x64.exe/download)) or `develop/7` ([`7.2.6-rc1`, built October 2018](https://sourceforge.net/projects/virtuoso/files/virtuoso/7.2.6-dev/Virtuoso_OpenSource_Server_7.20.x64.exe/download)).  (If you can build your own, the latest [`develop/7` codebase](https://github.com/openlink/virtuoso-opensource/commits/develop/7) includes a number of additional patches since the latest prebuilt binary.)

(I noticed that your current installation is in `C:/Program Files (x86)/`, but Virtuoso 7 is 64-bit only.  This location will not cause problems, but can cause confusion, so it should probably be moved to `C:/Program Files/`.)

If this issue persists in the new versions, we'll dig further into it.

**Comment by GeraldGrootRoessink** [comment]
I downloaded the prebuilt 7/develop through the link provided above, I get this version info:
> Virtuoso Open Source Edition (multi threaded)
> Version 7.1.0.3217-threads as of Sep  6 2017
> Compiled for Win64 (x86_64-generic-win-64)
> Copyright (C) 1998-2017 OpenLink Software

The bulkloader works perfect, but the version is lower the @TallTed mentioned.
Is the mirror site up-to-date?
