### ISSUE TITLE
COUNT(DISTINCT ?var) for unbounded ?var projects incorrect value

### ISSUE THREAD

**Issue by jindrichmynarz** [openlink/virtuoso-opensource#90]
Virtuoso (tested on version 07.00.3203 deployed on [DBPedia](http://dbpedia.org/sparql)) projects incorrect value for `COUNT(DISTINCT ?var)` when the `?var` isn't bounded. [Section 18.5.1.2 of the SPARQL 1.1 Query specification](http://www.w3.org/TR/sparql11-query/#defn_aggCount) states that in such cases _zero_ should be returned. However, Virtuoso returns `1`.

For example, the following query (see [results](http://dbpedia.org/sparql?default-graph-uri=http%3A%2F%2Fdbpedia.org&query=PREFIX+dc%3A+++%3Chttp%3A%2F%2Fpurl.org%2Fdc%2Felements%2F1.1%2F%3E%0D%0APREFIX+foaf%3A+%3Chttp%3A%2F%2Fxmlns.com%2Ffoaf%2F0.1%2F%3E%0D%0A++++%0D%0ASELECT+%3Fs+%28COUNT%28DISTINCT+%3Funbound%29+AS+%3Fcount%29%0D%0AWHERE+%7B%0D%0A+%3Fs+foaf%3Aname+%5B%5D+.%0D%0A+OPTIONAL+%7B%0D%0A++%3Fs+dc%3Anonexistent+%3Funbound+.%0D%0A+%7D%0D%0A%7D%0D%0AGROUP+BY+%3Fs%0D%0ALIMIT+1&format=text%2Fhtml&timeout=30000&debug=on)) shows this incorrect behaviour:

```
PREFIX dc:   <http://purl.org/dc/elements/1.1/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

SELECT (COUNT(DISTINCT ?unbound) AS ?count)
WHERE {
  ?s foaf:name [] .
  OPTIONAL {
    ?s dc:nonexistent ?unbound .
  }
}
GROUP BY ?s
LIMIT 1
```

More detailed discussion of this issue can be found in [this question on answers.semanticweb.com](http://answers.semanticweb.com/questions/24482/sparql-count-distinct-unbound-variables-whats-correct-implementation).

**Comment by HughWilliams** [comment]
Note the fix for this issue is now available on the Virtuoso open source git develop/7 branch:

SQL> SPARQL PREFIX dc:   http://purl.org/dc/elements/1.1/ PREFIX foaf: http://xmlns.com/foaf/0.1/      SELECT ?s (COUNT(DISTINCT ?unbound) AS ?count) WHERE {  ?s foaf:name [] .  OPTIONAL {   ?s dc:nonexistent ?unbound .  } } GROUP BY ?s LIMIT 1;
s                                                                                 count
VARCHAR                                                                           VARCHAR

---

http://fr.dbpedia.org/resource/Everytime_We_Touch_(chanson_de_David_Guetta)       0

1 Rows. -- 762 msec.
SQL> status('');
REPORT
VARCHAR

---

OpenLink Virtuoso  Server
Version 07.10.3210-pthreads for Linux as of Jun 11 2014 
Started on: 2014-06-11 16:34 GMT+2

Also, LOD has been updated with a fix for it, see http://bit.ly/UohWWN

**Comment by HughWilliams** [comment]
Note the fix for this issue is now available on the Virtuoso open source git develop/7 branch:

SQL> SPARQL PREFIX dc:   http://purl.org/dc/elements/1.1/ PREFIX foaf: http://xmlns.com/foaf/0.1/      SELECT ?s (COUNT(DISTINCT ?unbound) AS ?count) WHERE {  ?s foaf:name [] .  OPTIONAL {   ?s dc:nonexistent ?unbound .  } } GROUP BY ?s LIMIT 1;
s                                                                                 count
VARCHAR                                                                           VARCHAR

---

http://fr.dbpedia.org/resource/Everytime_We_Touch_(chanson_de_David_Guetta)       0

1 Rows. -- 762 msec.
SQL> status('');
REPORT
VARCHAR

---

OpenLink Virtuoso  Server
Version 07.10.3210-pthreads for Linux as of Jun 11 2014 
Started on: 2014-06-11 16:34 GMT+2

Also, LOD has been updated with a fix for it, see http://bit.ly/UohWWN
