### ISSUE TITLE
Docker container cannot access previous container data

### ISSUE THREAD

**Issue by kuzeko** [openlink/virtuoso-opensource#900]
I'm using the docker image `openlink/virtuoso-opensource-7:latest`

```bash
docker run --name ${CONT_NAME}  -d \
               --volume `pwd`/database:/database \
               --volume `pwd`/settings:/settings \
               -v `pwd`/import:/import  \
               --env DBA_PASSWORD=dba \
               -t -p 1111:1111 -p 8890:8890 -i openlink/virtuoso-opensource-7:latest
```

Then I'm starting the CLI and loading the data:

```bash
docker exec -it ${CONT_NAME}  isql 1111

OpenLink Virtuoso Interactive SQL (Virtuoso)
Version 07.20.3230 as of Feb  4 2020
Type HELP; for help and EXIT; to exit.
Connected to OpenLink Virtuoso
Driver: 07.20.3230 OpenLink Virtuoso ODBC Driver


delete from DB.DBA.load_list;
ld_dir ('/import', 'data.ttl.gz', 'http://example.com/data');
rdf_loader_run ();

sparql  select ?g count(*) where { graph ?g { ?s ?p ?o }  } group by ?g ;


g                                                                                 callret-1
LONG VARCHAR                                                                      LONG VARCHAR
_______________________________________________________________________________

urn:activitystreams-owl:map                                                       2
http://example.com/data                                                           122833228
http://www.openlinksw.com/schemas/virtrdf#                                        2479
http://localhost:8890/DAV/                                                        2963
http://www.w3.org/2002/07/owl#                                                    160
http://www.w3.org/ns/ldp#                                                         3
http://localhost:8890/sparql                                                      14
```

Then I stop the container , turn it on and query it,... **and it's empty**

```bash
docker stop ${CONT_NAME}
docker start ${CONT_NAME}
docker exec -it ${CONT_NAME} isql 1111

OpenLink Virtuoso Interactive SQL (Virtuoso)
Version 07.20.3230 as of Feb  4 2020
Type HELP; for help and EXIT; to exit.
Connected to OpenLink Virtuoso
Driver: 07.20.3230 OpenLink Virtuoso ODBC Driver
sparql  select ?g count(*) where { graph ?g { ?s ?p ?o }  } group by ?g ;
g                                                                                 callret-1
LONG VARCHAR                                                                      LONG VARCHAR
_______________________________________________________________________________

urn:activitystreams-owl:map                                                       2
http://www.openlinksw.com/schemas/virtrdf#                                        2479
http://localhost:8890/DAV/                                                        2963
http://www.w3.org/2002/07/owl#                                                    160
http://www.w3.org/ns/ldp#                                                         3
http://localhost:8890/sparql                                                      14
```

But, this is strange, because the data is there:

```bash

docker exec -it ${CONT_NAME} /bin/bash
root@c2b8413df672:/opt/virtuoso-opensource/database# ls -alh
total 1.6G
drwxr-xr-x 2     1001     1001 4.0K Feb 24 12:26 .
drwxr-xr-x 1 virtuoso virtuoso 4.0K Feb  4 15:15 ..
-rw-r--r-- 1 root     root     2.0M Feb 24 12:26 virtuoso-temp.db
-rw-r--r-- 1 root     root     1.6G Feb 24 12:26 virtuoso.db
-rw-r--r-- 1     1001     1001 6.9K Feb 24 11:05 virtuoso.ini
-rw-r--r-- 1 root     root       11 Feb 24 12:26 virtuoso.lck
-rw-r--r-- 1 root     root     3.9K Feb 24 12:26 virtuoso.log
-rw-r--r-- 1 root     root        0 Feb 24 11:06 virtuoso.pxa
-rw-r--r-- 1 root     root      185 Feb 24 12:26 virtuoso.trx

```

**Comment by HughWilliams** [comment]
As indicated in the [Bulk Loader](http://vos.openlinksw.com/owiki/wiki/VOS/VirtBulkRDFLoader) documentation:

```
6. Note at the end of the Bulk Load process the checkpoint command *MUST* be run to commit the bulk loaded data to the Virtuoso database file. This is because the default log_enable = 2 mode used by the bulk loader turns off transaction logging, thus if the database is shutdown before a checkpoint is run all the bulk loaded data would be lost. The bulk loader also disables checkpointing and the scheduler, which also need to be re-enabled post bulk load.

checkpoint;
checkpoint_interval(N);
scheduler_interval(M);
```

Thus I assume a checkpoint was not run before you restarted the docker, so you need to bulk load again and ensure a checkpoint is run when complete ...

**Comment by kuzeko** [comment]
Thanks, I've missed that, I've used virtuoso in docker for the past year+ (didn't upgraded since) and only got this problem with this upgrade.

Yet, let me ask:
1- why the loader disables the checkpoint but does not reneable it? Or at least produce a warning?

2- *most important* why can I query my data and the when I restart the data is not there? We are discussing about 1GB of data, how can it be so volatile? I'm asking because I've a PhD in Databases, so this is very interesting for me to understand.

**Comment by HughWilliams** [comment]
The change to disable checkpointing and scheduler interval was recently made, which is why you did see this before, but we have always recommended to disable checkpointing manual as you don't want to be checkpoint the database during a bulk load.

1-  When bulk loading data typically you run with multiple `rdf_loader_run()` process for optimal load rates, and it is not readily discernible when the last loader has completed to then re-enable checkpoint, hence it is documented at the end of the bulk loader process. 

2- Virtuoso functions in `read_uncommitted` isolation level by default which means pages written to the database that are now yet committed, with a checkpoint can be `read`. But if you stop the database before performing a checkpoint on restart any pages that were marked as uncommitted will be discarded as they were not explicitly committed. If you want to have the bulk loaded data to be persisted post a restart without a checkpoint, then you should bulk load with `rdf_loader_run(log_enable=>3)` as detailed in the bulk loader documentation, which then enables database transaction logging with all operations written to the Virtuoso transaction log file (`virtuoso.trx`) and would then be replayed on database restart committing the data to the database ie you would not lose the bulk loaded data.

**Comment by kuzeko** [comment]
Thanks for the great explanation, now I have the full picture.

1- I would expect every loader run to re-enable checkpoint and run a checkpoint at the end. But I guess other people expect other options.

2- I understand. Very interesting. But then, why the disk space is not freed at restart? So when I shut down  I still see the `.db` file being `1.6GB`?

**Comment by HughWilliams** [comment]
1- You don't want every loader to reenable checkpoints as it is not known when all loaders will complete and you do not want checkpoints to occur will bulk loading data. So we need to determine when all loader are complete or when the last one completes and then have it reenable checkpointing.

2- Virtuoso does not release allocated space that becomes unused as it assume the space will soon be reused and thus leaves it in place rather than releasing and then having to reallocate space which would affect performance.

**Comment by kuzeko** [comment]
Thanks, I will close this now, but I have two last questions to see if I understand correctly:

1- So you say that is safe to run multiple loaders in parallel?

2- So the space there is actually "empty" files?

**Comment by HughWilliams** [comment]
1- Yes, it has always been possible and recommended to run multiple `rdf_loader)run()` processes based on the number of available CPUs when bulk loading data for maximum platform utilisation, as detailed in the  [RDF Bulk Loader](http://vos.openlinksw.com/owiki/wiki/VOS/VirtBulkRDFLoader) documentation.

2- Unless you have stripped the database there will be only be on `virtuoso.db` file, it is the allocated file `pages` that would be empty or marked as unused and thus can be used again without the need to create a new page.
