### ISSUE TITLE
FCT & web indexing security issue

### ISSUE THREAD

**Issue by jakubklimek** [openlink/virtuoso-opensource#991]
I have encountered a security issue on all (my) deployed fct instances.

When accessing `/describe/?url=http://does.not.exist`, HTTP 404 code is returned when no data is found.
![image](https://user-images.githubusercontent.com/718827/137145503-c38dd0e2-3524-4e30-884d-87c637ecebd8.png)

However, `/fct/rdfdesc/usage.vsp?g=blabla/ddd` returns HTTP 200 and prefixes the query string with `http://` when displayed, even though there is no graph `blabla/ddd`.
![image](https://user-images.githubusercontent.com/718827/137145360-b0ab9d66-9b72-4257-a57f-3d3358c4b19a.png)

The problem is, that the second URL `/fct/rdfdesc/usage.vsp` gets indexed by Google and Bing, since it returns 200 and not 404. Combined with the fact that any URL can be inserted into the `?g` parameter, which allows anyone to generate a page with an arbitrary URL link, which is indexable by search engines, and the fact that there is, by default, no "noindex" tag leads to this currently being actively exploited (note the About URLs):
![image](https://user-images.githubusercontent.com/718827/137145972-8e377b0b-cac6-4715-aa7f-c491312037e5.png)

by pages such as this one hxxps://sefireef.xyz/sipgirlsxyz153.html (changed https to hxxps on purpose, to avoid accidental click) creating huge lists of URLs with malicious URLs in the param.

**Comment by TallTed** [comment]
@pkleef @kidehen @HughWilliams @openlink @imitko --

Please look into this reported vulnerability in FCT

**Comment by HughWilliams** [comment]
We are looking into the issue and will report back on our findings ...

**Comment by kidehen** [comment]
@jakubklimek,

Thanks for spotting the issue. 

We are going to get it fixed.

**Comment by pkleef** [comment]
I [committed a number of fixes on develop/7](https://github.com/openlink/virtuoso-opensource/commits?branch=develop/7&since=2021-10-14&until=2021-10-16) including several fixes for the FCT package. 

The patches  you requested are:

   * [return 404 when url does not exist](https://github.com/openlink/virtuoso-opensource/commit/465dba9b900b9cf4d32bfa6bc4e0696b9da73a66)
   * [added noindex on usage.vsp](https://github.com/openlink/virtuoso-opensource/commit/2cb38d5be74196b1075225c5c9766861f6a066dd)
