### ISSUE TITLE
Security (CVE-2021-44228): Log4Shell

### ISSUE THREAD

**Issue by SommerEngineering** [openlink/virtuoso-opensource#999]
This project seems to contain an outdated version of Log4j (version 1.x), at least according to GitHub's search results 😕 . Does this only affect the test versions or the release versions as well? I downloaded the latest release for Linux as a `*.tar.gz` file and could not find any Log4j library 👍 . Can you confirm that Virtuoso is not affected by this CVE, though? 🙂

**Comment by smalinin** [comment]
Log4j Java library used by Jena2 and Jena3 (and old Sesame) isn't part of Virtuoso. We distribute only DB access providers for Jena (and old Sesame), and these providers are used by Jena (and old Sesame) applications. The DB access providers for Jena connect to Virtuoso via TCP/IP connection, so CVE may be on Jena app side, but I think that new Jena versions were updated to use more recent Log4j already. 

p.s.
Now Sesame is RDF4J, and it uses newer Log4j version.

**Comment by HughWilliams** [comment]
See also the following document on  [Evaluation of the Log4J / CVE-2021-44228 vulnerability](https://community.openlinksw.com/t/evaluation-of-the-log4j-cve-2021-44228-vulnerability/2902) on OpenLink products, including Virtuoso ...

**Comment by SommerEngineering** [comment]
Thank you for your quick responses 👍 🙂

**Comment by pkleef** [comment]
To make absolutely clear, our `Jena`, `Sesame`, `RDF4J` Providers, as well as our `JDBC` Driver, for Virtuoso, do not use this `log4J API` in themselves. Some of the frameworks we used to built our Providers did historically use this API (e.g., for their test suite) which is why you see historical references in the `CLASSPATH` for building these providers.

There *are* references to the `log4j 1.x API` inside the `binsrc/tests/bsbm` which is a standalone benchmark built in cooperation with the University of Berlin. This code is published more for historical reasons than anything else, and may be removed at some future point if it causes confusion. It is, however, a client side application that can be used for testing, but is *never* installed so cannot be used for a remote attack on your system.

Finally, there are no versions of `log4.jar` inside our source tree nor shipped in any of our binary installers.
